### ISSUE TITLE
[Feature panel] Add observation

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#10]
User selects a map feature and clicks the "Add" button in the side panel to start filling out a new empty form.

@hintzemichael Could you kindly paste mocks for this (possibly w/redlines) into this issue?

**Comment by dhvogel** [comment]
Assuming that [this](https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZb2iviPIZTOF/files/MCEJu8Y2hyDScSOUrSBm4_v8gCZK1S-lZ5Q) is the mock you are referring to above.

If the user clicks the "Add Observation" button to add an observation, how does the user tie that observation to a particular point on the map. Would the user need to click the "Add Observation" button and then click the point on the map to which the observation should be added?

**Comment by gino-m** [comment]
Yep, this is the mock:
![image](https://user-images.githubusercontent.com/228050/64058795-627a2280-cb7e-11e9-9617-572e80b3a75b.png)

>If the user clicks the "Add Observation" button to add an observation, how does the user tie that observation to a particular point on the map. Would the user need to click the "Add Observation" button and then click the point on the map to which the observation should be added?

The side panel only shows after a map feature (point/line/polygon) has been selected. The observation would be associated with the selected feature.
