### ISSUE TITLE
[Feature panel] Show field labels instead of ids

### ISSUE THREAD

**Issue by gyarill** [google/ground-platform#105]

**Comment by gino-m** [comment]
@dhvogel Hi Dan! Assigning to you in case this is in your queue for next week. If not please lmk!

**Comment by dhvogel** [comment]
Based on the data structure provided by @gino-m [here](https://github.com/google/ground-platform/issues/9#issuecomment-507716546) it's unclear where you would find field labels. Where in the data structure are they stored?

**Comment by gino-m** [comment]
> Based on the data structure provided by @gino-m [here](https://github.com/google/ground-platform/issues/9#issuecomment-507716546) it's unclear where you would find field labels. Where in the data structure are they stored?

Good q. If you create a form through the UI (add a layer, then click "Customize" in the overflow form), you can see example data in the JSON editor (`<>` button next to the project name). The form layout, schema, and other metadata all live under the project definition always present in the store. Pasting an example here for reference:

```js
{
  acl: {
    ...
  },
  featureTypes: {
    naAVdFOVoE9zDhdF3o7G: {
      forms: {
        t38U6jlEp8BwB0SN4XSf: {
          elements: [
            {
              id: 'MkieWtEX27WqsgvRPIHD',
              labels: {
                _: 'Field 1'
              },
              required: false,
              type: 'text_field'
            },
            {
              cardinality: 'select_one',
              id: '3V2EzMJ5CS5iCC6kRlIK',
              labels: {
                _: 'Field 2'
              },
              options: [
                {
                  code: 'A',
                  labels: {
                    _: 'Alpha'
                  }
                },
                {
                  code: 'B',
                  labels: {
                    _: 'Beta'
                  }
                }
              ],
              required: true,
              type: 'multiple_choice'
            }
          ],
          titles: {
            _: 'Test form'
          }
        }
      },
      itemLabel: {
        _: 'Test layer'
      }
    }
  }
}
```

**Comment by dhvogel** [comment]
Ok. I think this makes sense. Let me state my assumptions about this data structure to make sure we are on the same page.

`naAVdFOVoE9zDhdF3o7G` - the `featureId`
`t38U6jlEp8BwB0SN4XSf` - the `formId`
`3V2EzMJ5CS5iCC6kRlIK` - the `fieldId`

Give this a post a thumbs up if these assumptions are correct.

**Comment by gino-m** [comment]
👍 to all but this one:

> `naAVdFOVoE9zDhdF3o7G` - the `featureId`

That's the `featureTypeId`. The actual feature themselves aren't part of the project metadata/schema definition described here.

Note that `featureTypeId` will eventually be renamed to `layerId`.

HTH!
