### ISSUE TITLE
[Feature panel] Update styling to match latest mocks

### ISSUE THREAD

**Issue by gyarill** [google/ground-platform#106]

**Comment by gyarill** [comment]
@gino-m, the mocks that I know of are marked obsolete https://markup.googleplex.com/projects/1941/v/1?mode=preview . Do we have new once somewhere?

**Comment by gino-m** [comment]
![image](https://user-images.githubusercontent.com/228050/63656580-af678e80-c763-11e9-9f9a-318e4db101e5.png)

**Comment by gino-m** [comment]
Obsolete; will be reimplemented in new version.
