### ISSUE TITLE
[Code health] Replace `obj | null` with `obj?` or `obj | undefined` wherever allowed

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1064]

**Comment by semla** [comment]
I took a look at this, but all the streams from [NavigationService](https://github.com/google/ground-platform/blob/master/web/src/app/services/navigation/navigation.service.ts#L61C3-L61C3l) use [HttParams](https://angular.io/api/common/http/HttpParams#get) that returns `string | null`.
So I ended up with only 6 files modified. Can post a PR if you want to take a look?

**Comment by gino-m** [comment]
@semla Sure, thanks for taking a look!

**Comment by gino-m** [comment]
This code health FR is not technically consistent with the definitions of `undefined` and `null`; `null` should be used when a value is known to be missing, `undefined` should be used when the value has not been initialized or passed as an arg.
