### ISSUE TITLE
Implement LOI editor page in "create survey" flow

### ISSUE THREAD

**Issue by nwkotto** [google/ground-platform#1069]
![image](https://github.com/google/ground-platform/assets/228050/aa8d7b35-fc6d-44d2-97e1-9754023be61b)

[latest design](https://www.figma.com/file/r2uGtyOiWoDa29za7DNuUc/Ground-Acacia-UX?node-id=604%3A28674)

Basic features:
- Map: Pull straight from map.component.ts
- List of LOIs: Get logic from map.component.ts -- think it relies on some service
- Import button: Button opens up import-dialog.component.ts -- check jobs list for how this is done
- Deleting LOIs: I dunno, but again, I think you should be able to pull this logic straight from map.component.ts

This will be living inside create-survey.component.ts , but needs to be its own component

**Comment by gino-m** [comment]
> There is a drawing tool and a drag and drop tool in the existing map component. Daoyu mentioned that we should disable these for the LOI editor.

They should be disabled for now, until we define how they will work for manual edits.
