### ISSUE TITLE
[Feature panel] Show layer name and icon above record list

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#107]

**Comment by dhvogel** [comment]
Similar to my comment [here](https://github.com/google/ground-platform/issues/105#issuecomment-526704139), where in the record data structure would you like to store layer name and icon. Could you provide an updated data structure?

**Comment by gino-m** [comment]
Sure.. please see https://github.com/google/ground-platform/issues/105#issuecomment-526795549 for an example. Lmk if you have any questions!

**Comment by dhvogel** [comment]
even when looking at the data structure linked above it's unclear to me where the layer name and the icon are. could you specify the fields within the data structure where layer name and icon are stored?

**Comment by gino-m** [comment]
The icon would just be the fixed map marker icon for now, since there's currently no way to change it.

The layer name is currently at `project.featureTypes[featureTypeId].itemLabel['_'].

Sorry this is still poorly documented. I'll ping you the draft design doc now.

**Comment by gino-m** [comment]
@dhvogel ok to close
