### ISSUE TITLE
Wrong page when starting a new survey and looking at demo one

### ISSUE THREAD

**Issue by os-micmec** [google/ground-platform#1096]
**Describe the bug**
We get this page 
<img width="632" alt="Screenshot 2023-06-02 at 11 52 56 AM" src="https://github.com/google/ground-platform/assets/92086423/1d88cc4b-d6d8-457c-8d5f-f01e8cb0439b"> when interacting between Demo survey and Start a new survey workflow.

**To Reproduce**
1. Run `npm run start:local
2. Go to the http://localhost:5000/surveys page
3. Click on "Demo Survey"
<img width="764" alt="Screenshot 2023-06-02 at 11 53 45 AM" src="https://github.com/google/ground-platform/assets/92086423/d434158b-6a4c-4e4f-bf4a-0a0dfe7bb550">
5. Once the Demo Survey loads, navigate back with the browser left arrow to go back to the surveys page.
6. Now click on "Start new survey"
7. You should see the wrong page load up.

**Expected behavior**
On step 6, we should see 
<img width="1311" alt="Screenshot 2023-06-02 at 11 56 25 AM" src="https://github.com/google/ground-platform/assets/92086423/46ae2b07-3c62-40a9-93cb-dee4133f11e4"> instead of
<img width="632" alt="Screenshot 2023-06-02 at 11 52 56 AM" src="https://github.com/google/ground-platform/assets/92086423/1d88cc4b-d6d8-457c-8d5f-f01e8cb0439b">

**Comment by gino-m** [comment]
On dev server we see this when creating survey:

<img width="1468" alt="image" src="https://github.com/google/ground-platform/assets/228050/5c88299b-f218-44d5-802d-34b77087c59d">
