### ISSUE TITLE
[Feature panel] Delete feature

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#11]
Let's add the "Delete" entry to an overflow menu in the top-right of the feature details in the side panel when the feature is selected. Deleting the feature should also delete all related observations; we should show a BSW (big scary warning) confirmation dialog before doing this, i.e. "Deleting this map feature will delete all associated data, including any collected observations. This cannot be undone. Are you sure?" @sergeydolgov1 fyi/for comment.

**Comment by sergeydolgov1** [comment]
@gino-m Proposed feature and the flow SGTM
