### ISSUE TITLE
[Feature] Re-refactor survey creation flow

### ISSUE THREAD

**Issue by DaoyuT** [google/ground-platform#1171]
- Add a state to survey. So far we need 2: Draft(creation flow not complete), Onboarded(creation flow completed). 
   - The name just need to make sense for the current situation, we can rename them later.
   - In the future, we may include more states like Testing, Deprecated, etc.
 - In the creation page, we won't direct users to a specific step anymore, we will always show them the 1st step, with previously saved data
 - Navigation
   - From survey list page, go to
     - map page, if creation flow completed
     - create survey page, if creation flow NOT completed
   - From create survey page, go to
     - edit page, if creation flow completed
   - From edit survey page, go to
     - create survey page, if creation flow NOT completed

**Comment by gino-m** [comment]
@DaoyuT this likely is out of sync w/ the current code, I vote we mark "Obsolete".
