### ISSUE TITLE
Task editor doesn't resize based on contents

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1199]
Buttons and task editor widgets appear outside of the background card.

<img width="2032" alt="image" src="https://github.com/google/ground-platform/assets/228050/06afebdf-b646-4b85-ad68-00f9add28de7">

@rfontanarosa PTAL? @os-micmec FYI

**Comment by rfontanarosa** [comment]
it doesn't happen on my macos (chrome 117)
