### ISSUE TITLE
[Map] Move/reposition points

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#12]

**Comment by gino-m** [comment]
Hi @DaoyuT! As this is related to the map, could you take this one on?

@jacobmclaws, what would a potential flow for editing the location of an existing pin look like?

**Comment by sergeydolgov1** [comment]
Latest UXD Suggestions:
A) Point Hover State:

![image](https://user-images.githubusercontent.com/20148684/86861077-1855ad80-c07b-11ea-8446-9ca51cb68cf8.png)

**Comment by sergeydolgov1** [comment]
Latest UXD Suggestions:
A) Point Drag State:

![image](https://user-images.githubusercontent.com/20148684/86861135-31f6f500-c07b-11ea-889b-745daf7e4a8f.png)

**Comment by gino-m** [comment]
@sergeydolgov1 @jacobmclaws Re dragging to reposition; is there any concern that users will accidentally reposition points, while dragging the map for example? I believe moving points once they've been added will be very rare; in that case, should we require users to do something first to enter an "editing" state. One option could be a button "Edit position" on the feature details page that will show crosshairs for the user to relocate the point. This would also bring the edit flow closer to add flow.. Any thoughts?

**Comment by sergeydolgov1** [comment]
> @sergeydolgov1 @jacobmclaws Re dragging to reposition; is there any concern that users will accidentally reposition points, while dragging the map for example? I believe moving points once they've been added will be very rare; in that case, should we require users to do something first to enter an "editing" state. One option could be a button "Edit position" on the feature details page that will show crosshairs for the user to relocate the point. This would also bring the edit flow closer to add flow.. Any thoughts?

@gino-m @jacobmclaws I think that is a valid point. Perhaps the flow can be 1) Click on a "Edit position" button --> 2) drag point to reposition --> 3) Click "Save changes" button (there may also be "Cancel" button that resets point location to its initial position)

**Comment by gino-m** [comment]
@jacobmclaws wdyt?

**Comment by sergeydolgov1** [comment]
@gino-m @DaoyuT 
Sharing the latest mocks (see attached)
Question: What are the actions that are available to users when they select "Edit" mode? Are they able only to rename points/features? If that's the case, perhaps we should change "Edit" to "Rename"?
[Reposition Feature Flow.pdf](https://github.com/google/ground-platform/files/4963862/Reposition.Feature.Flow.pdf)

**Comment by gino-m** [comment]
@sergeydolgov1 @jacobmclaws  Since we won't have a "Features List" per se at the moment, where should the "Move" button be placed? Would this go in the panel header when the feature is selected and we're showing the observation list? @DaoyuT is about to start working this.

**Comment by sergeydolgov1** [comment]
@gino-m @jacobmclaws @DaoyuT 
Sharing the latest Mocks:
1. User selects a point to reposition
![image](https://user-images.githubusercontent.com/20148684/90293220-7161ef80-de38-11ea-86c4-c8569805480e.png)

2. Selected point becomes bigger and triggers pop-up menu with "Reposition" button
![image](https://user-images.githubusercontent.com/20148684/90293389-d1589600-de38-11ea-8410-0874717035a4.png)

3. User drags Point to a new location and clicks on "Save Changes" in the upper right corner when they're done
![image](https://user-images.githubusercontent.com/20148684/90293519-1b417c00-de39-11ea-995d-fbb9a879b393.png)

Additional comments:
- For the MVP we enable only "Add Point" functionality, meaning only "Point" icon will be available the lower left corner. Should be like this:
![image](https://user-images.githubusercontent.com/20148684/90293667-7a9f8c00-de39-11ea-87d6-b626a5c293c2.png)

- "Save changes" button in the upper corner should be augmented with "Cancel". If user clicks on "Cancel" during repositioning, Point location resets to the initial one and user exists "Reposition" flow

- Point list shouldn't have dropdown but overflow menus. Should look like this:
![image](https://user-images.githubusercontent.com/20148684/90293915-0dd8c180-de3a-11ea-8f31-7fa615063873.png)

**Comment by gino-m** [comment]
Hi @DaoyuT, let's consider this as done, with additional changes as enhancements. Great work!
