### ISSUE TITLE
[Map] Pins sometimes disappear when panning map

### ISSUE THREAD

**Issue by DaoyuT** [google/ground-platform#122]
When zoomed out far enough that there are 2 Africas on the map, the pins in Africa will only display on one of the 2 Africas, and the pins will bounce back/force when dragging the map left/right.

<img width="594" alt="Screen Shot 2019-09-10 at 2 54 37 PM" src="https://user-images.githubusercontent.com/10445677/64641861-06fc3000-d3db-11e9-91ce-46afc56ad1f8.png">
<img width="610" alt="Screen Shot 2019-09-10 at 2 54 48 PM" src="https://user-images.githubusercontent.com/10445677/64641865-09f72080-d3db-11e9-8d20-27e7ee0a5909.png">

**Comment by gino-m** [comment]
Obsolete; will be reimplemented in new version.
