### ISSUE TITLE
Update side menu to latest mocks

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1241]
![image](https://github.com/google/ground-platform/assets/228050/2db6f1eb-6c52-4c7e-9c4b-7c6ac913ceca)

**Comment by K-Vishwak** [comment]
I will work on this. Can you explain how I can get started?

**Comment by gino-m** [comment]
> I will work on this. Can you explain how I can get started?

Sure! Please check out https://github.com/google/ground-platform/blob/master/CONTRIBUTING.md for instructions on how to get started. 

You can see details on styling, padding, margins, etc. in:
https://www.figma.com/file/r2uGtyOiWoDa29za7DNuUc/Ground-Acacia-UX?type=design&node-id=2541-53139&mode=dev

Pass: ground4good

**Comment by K-Vishwak** [comment]
Sure. I will go through and get start.

**Comment by K-Vishwak** [comment]
Hi @gino-m,

Do I need to set up firebase for local development?

Does it costs?

Thanks.

**Comment by gino-m** [comment]
> Hi @gino-m,
> 
> Do I need to set up firebase for local development?
> 
> Does it costs?
> 
> Thanks.

Instructions for starting the Firebase Emulator Suite described under https://github.com/google/ground-platform/blob/master/CONTRIBUTING.md#building-and-running-the-app run the emulator on your machine, nothing runs in the cloud in that case.
