### ISSUE TITLE
[CSV Export] "Other" (specify) not supported

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1249]
See also https://github.com/google/ground-android/issues/794

**Comment by gino-m** [comment]
See https://github.com/google/ground-android/issues/2202 for schema

**Comment by jcqli** [comment]
@os-micmec @gino-m This was left in iteration 4, do we know the current status?

**Comment by jcqli** [comment]
Chatted with @gino-m and moving this to prioritize for after TT date

**Comment by gino-m** [comment]
"Other" string is stored as another value in the along ids in the value array, surrounded by `"[ "` and `" ]"`.

**Comment by jcqli** [comment]
This may be addressed by the proto migration, may be able to deprioritize or close out without additional changes after the proto migratino is complete
