### ISSUE TITLE
[Code health] Enforce structure of data in Firestore at compile-time

### ISSUE THREAD

**Issue by os-micmec** [google/ground-platform#1277]
At the moment, our models are defined only in web, and we either don't use them or keep a copy of them in functions or android. We should consolidate on a single source of truth

**Comment by os-micmec** [comment]
Kotlin JS https://kotlinlang.org/docs/js-overview.html is a good option

**Comment by gino-m** [comment]
@jcqli Punting this to next milestone as discussed. Initial prototype is already checked in.

**Comment by gino-m** [comment]
Android and web JSON code generators are brittle, and deriving the model from JSON leads to additional complexity. If we want to share code, we may want to consider a project which exposes a hosted service or a shared client-side [KMP](https://kotlinlang.org/docs/multiplatform.html) lib. Closing this for now as infeasible.
