### ISSUE TITLE
Minor tweaks to edit survey flow

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1297]
In left menu:
- [x] Rename "Dashboard" to "Home"
- [ ] #1405
- [x] Rename "Survey settings" to "Survey details"
- [x] Change "Survey settings" icon from great to Material clipboard icon (outlined)

On the "Survey details" tab:

- [x] Add heading "Survey details"

Publish changes button:
- [x] Disable when there are no unsaved changes
- [x] Stay on edit survey screen after publishing changes instead of returning to home screen

On the home screen:
- [x] When clicking "gears" icon, show a menu with a single option (for now) saying "Edit survey"

@rfontanarosa PTAL?

**Comment by amegantz** [comment]
![image](https://github.com/google/ground-platform/assets/112978024/ba194243-5e36-4899-8491-0eef5d89c48e)
Take your pick!

**Comment by gino-m** [comment]
@rfontanarosa Can you please check and reopen or create issues if not all of these were done?

**Comment by gino-m** [comment]
Forked into #1297
