### ISSUE TITLE
[Form editor] Drag to reorder form fields

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#13]
Mock:
![image](https://user-images.githubusercontent.com/228050/48669624-a4961400-ead6-11e8-84d6-8879e6bea233.png)

Redlines:
![image](https://user-images.githubusercontent.com/228050/48669627-a9f35e80-ead6-11e8-9ab8-a93350c8a363.png)

**Comment by gino-m** [comment]
Note: Only drag handle (top part of form field card) should be draggable.

**Comment by gino-m** [comment]
@DaoyuT Hi! Any updates here? ⭐️

**Comment by DaoyuT** [comment]
https://github.com/google/ground-platform/pull/90 created
