### ISSUE TITLE
[Feature] Numeric Type Specifier for Question Tasks

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#1316]
The question task dropdown currently does not list a numeric type:

<img width="907" alt="Screenshot 2023-11-30 at 10 21 57 AM" src="https://github.com/google/ground-platform/assets/11237600/a8b08e8a-6868-4136-84a7-2a252587e5b6">

It'd be good to support this explicitly (I believe it's already converted correctly when the text is numeric).

@gino-m FYI

**Comment by rfontanarosa** [comment]
fixed here: https://github.com/google/ground-platform/pull/1331
