### ISSUE TITLE
Side drawer/hamburger menu doesn't do anything

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#1318]
**Describe the bug**
Clicking the side drawer menu currently doesn't do anything.

**To Reproduce**
1. Create a new survey 
2. Click the side navigation icon

**Expected behavior**
The side drawer collapses and is hidden.

**Video**
https://github.com/google/ground-platform/assets/11237600/71b6f706-0cf3-4b2a-86df-ef291de90c19

@vittorino for design

**Comment by gino-m** [comment]
See #1363
