### ISSUE TITLE
help for a demo deployment 

### ISSUE THREAD

**Issue by 12rambau** [google/ground-platform#1342]
As discussed in the last FDaP meeting, I would like to launch a demo firebase instance of Ground to convince my company to start using Ground instead of other solutions. 
I would need something like what @gino-m presented at Geo4Good, and I'm positive I can onboard anybody from my side. 

Do you think it's doable? if yes can someone like @rfontanarosa (sorry to ping you but @lecrabe told me you were THE man of the situation 😄 ) guide me through a simple demo deployment ?

**Comment by gino-m** [comment]
Hi @12rambau, thanks for your interest in promoting the platorm! We still have a few kinks to work out, not least updating the build and deploy docs. If you like you can subscribe the https://github.com/google/ground-platform/issues/1345 to get notified when there's progress on that front. Wdytt?

**Comment by 12rambau** [comment]
Done, thanks. 

Nonetheless, I need to advocate between Ground and Fulcrum (ESRI product) this Thursday so anything where I can move a mouse and create a plot will help support my case, the web portal is unfortunately not sufficient.

I'm happy to play beta tester of the deployment method and help you with the documentation (ask SEPAL people, I'm a documentation person)

**Comment by gino-m** [comment]
Closing this public tracker for now, let's continue to communicate by email.
