### ISSUE TITLE
Integrate survey JSON editor into draft survey service

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1356]
- [ ] The state of the current draft should be represented in the JSON editor
- [ ] Editing the JSON should update the draft survey in memory on blur
- [ ] The Save button should be removed
- [x] Hide the JSON editor unless the user clicks "Manage survey" while holding a modifier key (exact key TBD)
- [x] Hide this interface for now? Maybe only show when ?debug=true in URL

"Publish changes" can then be used to save the modified JSON.

**Comment by gino-m** [comment]
@rfontanarosa Can we hide this interface for now? Maybe only show when ?debug=true in URL or similar?

**Comment by rfontanarosa** [comment]
my fault. deploying the application as prod hides the JSON option.

**Comment by gino-m** [comment]
This is already implemented. @rfontanarosa will redeploy as "prod" to hide.
