### ISSUE TITLE
[Survey editor] Job not deleted when clicking "Remove job"

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1396]
Refreshing the page causes the job to return, even though I've published changes:

https://github.com/google/ground-platform/assets/228050/1fc36fca-e35e-4e5f-b6cc-8f5bc4cb25e1

Steps:

- [x] Verify that LOIs are removed when job is removed and user clicks "Publish changes"
- [x] Move updating of survey and deleting LOIs into a single [atomic Firestore transaction](https://firebase.google.com/docs/firestore/manage-data/transactions#web-modular-api)
- [x] Show a progress spinner while "Publish changes" is in progress

**Comment by gino-m** [comment]
We need to show a progress spinner while survey is updating.

**Comment by jcqli** [comment]
@gino-m @rfontanarosa Since work hasn't started yet suggest having a 20%er work on this in iteration 5 since Roberto has a lot on his plate the next couple weeks
