### ISSUE TITLE
[Side panel] Rename "Download submissions" menu item to "Download job data"

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1398]
@amegantz For potential veto 

<img width="537" alt="image" src="https://github.com/google/ground-platform/assets/228050/50a064d5-9f5b-42f5-89cc-bd6177b491f0">

@amysorto PTAL?

**Comment by amegantz** [comment]
Can you please clarify what "Download submissions" does? Does that download the data that collectors provided?

**Comment by gino-m** [comment]
> Can you please clarify what "Download submissions" does? Does that download the data that collectors provided?

That's correct. It also joins that data with the respective LOIs/site geometries and ids.

**Comment by amegantz** [comment]
Got it, thanks. I wonder if "Download CSV" might be best here since there's a risk "Download submissions" might be construed as a kind of sync rather than a file download

**Comment by gino-m** [comment]
> Got it, thanks. I wonder if "Download CSV" might be best here since there's a risk "Download submissions" might be construed as a kind of sync rather than a file download

That could work to. In the future a dialog will appear to allow you to choose the download format and structure. A community member just did the rename to "Download job data". Can we keep that for now?

**Comment by amegantz** [comment]
Works for me
