### ISSUE TITLE
[Form editor] Drag to reorder multiple choice options

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#14]
Drag handle is visible to left of "option" only on hover.

See latest mocks in #225.

**Comment by gino-m** [comment]
Hi @DaoyuT! Do you have any updates on this one?

**Comment by parulraheja98** [comment]
Hi @gino-m Can I take this issue?

**Comment by gino-m** [comment]
> Hi @gino-m Can I take this issue?

Hi @parulraheja98 we're currently reimplementing the layer modal in Angular under `web-ng/`. Would you like to take a different issue on the Angular impl?

**Comment by parulraheja98** [comment]
Hi @gino-m , Yes I can take different issue on Angular. Please link me to the issue 

Thanks

**Comment by gino-m** [comment]
Great! I just did a quick pass over the existing issues and updated the `good first issue` label. Please comment on any of these if they seem interesting:
https://github.com/google/ground-platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by parulraheja98** [comment]
Closed by #292
