### ISSUE TITLE
[Edit survey] Define behavior of job tabs (tasks/sites) when changing jobs

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1416]
This is the current behavior:

https://github.com/google/ground-platform/assets/10047945/31d34684-713c-4074-b900-abd457a1025d

@vittorino Should the "Sites" tab stay selected? What's the correct behavior here?

**Comment by vittorino** [comment]
yes that looks correct, when switching from tasks to sites the user is under the same job so it keeps the context

**Comment by gino-m** [comment]
> yes that looks correct, when switching from tasks to sites the user is under the same job so it keeps the context

@vittorino I was asking what happens when changing jobs, not between "Sites" and "Tasks"
