### ISSUE TITLE
[Code health] Instantiate LocationOfInterest class and deprecate its inherent classes(PointOfInterest, GeoJsonLocationOfInterest..)

### ISSUE THREAD

**Issue by DaoyuT** [google/ground-platform#1444]
Classes like `PointOfInterest` & `GeoJsonLocationOfInterest` that extends `LocationOfInterest` were introduced while we were migrating our data model. Now we should only use `LocationOfInterest` and this bug is to deprecate those child classes and replace all occasions with `LocationOfInterest`.

**Comment by gino-m** [comment]
Done in https://github.com/google/ground-platform/pull/1882
