### ISSUE TITLE
[Code health] Update developer documentation in Wiki

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1446]
Most pages are woefully out of date; hiding the Wiki until we can update docs to latest.

**Comment by gis-wes** [comment]
Would be nice to have a way to contribute to the wiki. Instructions did not work out of the box when onboarding.

**Comment by gino-m** [comment]
@gis-wes We're planning to move all docs to the website under `/docs` by EOY, at which point they'll be editable.

In the meantime, can you let us know which issues you've encountered and in which page and step? @rfontanarosa FYI

**Comment by gis-wes** [comment]
@gino-m So far, my observations have been on "First Time Setup" in the dev guide. I've been keeping a log of any friction in the setup process at https://github.com/users/gis-wes/projects/1/views/3. Not a lot of detail at the moment. I'm getting into functionality now. I'll keep recording what I find.

**Comment by gino-m** [comment]
> So far, my observations have been on "First Time Setup" in the dev guide. I've been keeping a log of any friction in the setup process at https://github.com/users/gis-wes/projects/1/views/3. Not a lot of detail at the moment. I'm getting into functionality now. I'll keep recording what I find. Is there an active community to ask questions when issues are encountered?

@gis-wes Just back and ramping back up. This friction log is excellent, very helpful. (@amegantz FYI) We've just transitioned to community ownership, so there is still no public discussion forum. Open to suggestions on platforms to use for this.

**Comment by rfontanarosa** [comment]
thank you @gis-wes, I've updated the guide yesterday (mainly with the web-app part). reading your friction list, it should fix three or four of your points.

**Comment by gino-m** [comment]
Closing in favor of #1722 since be moving that documentation to the website.

**Comment by gino-m** [comment]
@gis-wes Any chance you'd like to file the remaining frictions / FRs as bugs in `ground/ground-platform`? Once we have the docs in the repro, would you be interested in taking some of those fixes on?

**Comment by gis-wes** [comment]
@gino-m Sorry, got busy but I'm back now. I'll find what is remaining during my next install and file bugs.

Is there an inventory of existing functionality from a user standpoint? Would be glad to write docs while I walkthrough what exist. Wanted to catalog it before writing any feature requests for PRs I could submit. I've noticed a few gaps that I want to propose if they're actually missing. 

Looks like the community driven docs are still a work-in-progress. Wondering how to contribute while I ramp up.
