### ISSUE TITLE
[Edit survey] Select job doesn't update when selecting jobs on side panel

### ISSUE THREAD

**Issue by os-micmec** [google/ground-platform#1514]
When you open the edit survey page with multiple jobs, and you try to navigate from one job to another one, the page does not update with the tasks related to that job. Instead, it stays on the same job you landed on initially.

The URL updates, and if you refresh the page shows the correct tasks for the job you were trying to navigate to.

**Comment by gino-m** [comment]
This has been fixed, iirc by @rfontanarosa

**Comment by gino-m** [comment]
This has been fixed, iirc by @rfontanarosa. Please reopen if I'm wrong!
