### ISSUE TITLE
[Task editor] Show warning when deleting add LOI task

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1525]
Removing the "add LOI" task in the task editor will caused the "Data collectors can add new sites" to be disabled, i.e. data can only be collected for existing LOIs. @amegantz Can you lend a hand for exact UI copy?

**Comment by amegantz** [comment]
Is this in the Figma somewhere? How would this message show (toast, dialog, etc.)?

**Comment by gino-m** [comment]
Yes! It's here:

![image](https://github.com/google/ground-platform/assets/228050/259fc4eb-4b5a-4e4b-8dc5-e0357a37971e)

Tagging you there as well.

**Comment by amegantz** [comment]
![image](https://github.com/google/ground-platform/assets/112978024/cb207ae5-e646-42af-907b-957916e4b3b7)
How about this?

**Comment by gino-m** [comment]
> ![image](https://private-user-images.githubusercontent.com/112978024/310672535-cb207ae5-e646-42af-907b-957916e4b3b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjM1NDIsIm5iZiI6MTcwOTc2MzI0MiwicGF0aCI6Ii8xMTI5NzgwMjQvMzEwNjcyNTM1LWNiMjA3YWU1LWU2NDYtNDJhZi05MDdiLTk1NzkxNmU0YjNiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQyMjE0MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzhkMzQ0YjI2MzNhN2VhMTk0MGM5YTU3YjNmOGY3YjdkYTYyZTgxZjBmOGRlOTY4NjMyNjZjOGQ1ZmI2NjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7bxVO6TNqjGu_T8NVo43XuBEJ1aIAY2OdzMk5PaGnDY) How about this?

LG, though we should make it clear that this applies only to this job; there could be other jobs for which they can add sites.

**Comment by gino-m** [comment]
Thank you, @amegantz

**Comment by gino-m** [comment]
@DaoyuT I disabled the ability to delete LOI tasks, so we can close this one.
