### ISSUE TITLE
[Create/edit survey] Update LOI editor, remove "data collection strategy" screen

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1549]
- [ ] Remove "data collection strategy" screen in create survey flow
- [ ] Only show "imported" LOIs (not data collector LOIs) on map (exclude LOIs with `predefined: false`
- [ ] Update "Clear all" to only delete LOIs without `predefined: false`
- [ ] Warn user if clicking "Continue" with no LOIs imported and "data collectors can add" toggle off
- [ ] Update LOI editor to match attached designs. Exact language TBD (@gino-m @amegantz)

@vittorino @rfontanarosa FYI

**Comment by vittorino** [comment]
Step 1
![image](https://github.com/google/ground-platform/assets/679199/6814043a-8123-49ba-9ea3-cf99076bf523)

Step 2 (imported)
![image](https://github.com/google/ground-platform/assets/679199/cb73a4b2-ab41-4b59-baee-a11369ea0b76)
