### ISSUE TITLE
[LOI editor] Implementation incomplete

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1570]
- [x] "Clear all" should only delete predefined LOIs (without `planned: false`, i.e., if `null` or `true`)
- [x]  Map should only show predefined LOIs
- [x] Big scary warning should be shown when clicking "Clear all". @amegantz for copy, something like:
   > Clear predefined sites
   > This action will delete all predefined data collection sites. All associated data will be lost. Are you sure?

@rfontanarosa FYI

**Comment by amegantz** [comment]
```
Delete predefined sites

All predefined data collection sites and their associated sites will be permanently deleted.
[Cancel] [Confirm]
```

Trying to avoid ambiguity with the word "clear" in the context of sites, as that could be misinterpreted as marking data collection as complete, or even doing something in the physical site itself
