### ISSUE TITLE
"The requested action is invalid" after signing in

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1581]
This only occurs on tablet:

![image](https://github.com/google/ground-platform/assets/228050/31330eb0-8287-4919-8258-169caffbee8d)

Reported by @lecrabe

**Comment by gino-m** [comment]
@lecrabe will test on a different computer and/or network to see if the problem reoccurs.

**Comment by jcqli** [comment]
@lecrabe is this reproducable still?

**Comment by lecrabe** [comment]
Fixed now
