### ISSUE TITLE
[Code health] Handle missing value when image is skipped

### ISSUE THREAD

**Issue by rfontanarosa** [google/ground-platform#1583]
```
  getFirebaseImageURLs() {
    this.tasks?.forEach(task => {
      if (task.type === this.taskType.PHOTO) {
        const submissionImage = this.getTaskSubmissionResult(task)!
          .value as string;
        const imageRef = ref(this.storage, submissionImage);
        getDownloadURL(imageRef).then(url => {
          this.firebaseURLs.set(submissionImage, url);
        });
      }
    });
  }
```
```
submission.service.ts:91 ERROR TypeError: Cannot read properties of undefined (reading 'value')
    at submission-panel.component.ts:75:68
    at List.__iterate (immutable.es.js:3338:11)
    at List.forEach (immutable.es.js:4854:17)
    at SubmissionPanelComponent.getFirebaseImageURLs (submission-panel.component.ts:73:17)
    at Object.next (submission-panel.component.ts:61:16)
    at ConsumerObserver.next (Subscriber.js:113:33)
    at Subscriber._next (Subscriber.js:80:26)
    at Subscriber.next (Subscriber.js:51:18)
    at Subject.js:69:34
    at Object.errorContext (errorContext.js:22:9)
```

**Comment by gino-m** [comment]
Instead of throwing an error we should show the "Skipped" text as we do for other values. In the near future we'll make "skipped" explicit, but for now ok to rely on `null`.

@nwkotto Would you like to take this one?

**Comment by nwkotto** [comment]
It looks like this has already been fixed. The "Take a photo" section now says "Skipped" and I see a conditional in the code for that case that isn't in what Roberto posted.
![Screenshot 2024-07-19 at 2 42 46 PM](https://github.com/user-attachments/assets/d637b1a3-7f3a-4d4b-8655-c1b1d4745c3f)

There is a separate issue, which is that sometimes there's an image url but I get an "Object ... does not exist" error and the "Take a photo" section just appears blank 
![Screenshot 2024-07-19 at 2 45 38 PM](https://github.com/user-attachments/assets/b7a721e8-535c-481a-a22a-f725e9abf69d). Not sure if this is something the user will actually encounter, though, or it's just a message test database.
