### ISSUE TITLE
[Task editor] Temporarily disable ability to add "other" multiple choice question

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1586]

**Comment by gino-m** [comment]
Pending confirmation from @justinkimtang as to whether this feature will be available.

**Comment by jcqli** [comment]
https://github.com/google/ground-android/issues/794 tracking this feature

**Comment by gino-m** [comment]
@justinkimtang has sent a PR. @DaoyuT if that gets merged today or tomorrow we can close this as "won't fix".

**Comment by jcqli** [comment]
https://github.com/google/ground-android/issues/794 is closed with https://github.com/google/ground-android/pull/2340
