### ISSUE TITLE
[Layer dialog] Style editor component

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#159]
Substeps:
- [ ] Button with current pin style
- [ ] Clicking button toggles inline popup
- [ ] Inline popup shows the [ngx-color-picker](https://www.npmjs.com/package/ngx-color-picker) component
- [ ] Pin shown in button changes color based on color selection

![image](https://user-images.githubusercontent.com/228050/68367023-ab140600-0102-11ea-8ecc-bf8a1a6e702c.png)

Reference this issue in related PRs with "Work towards #159."

**Comment by parulraheja98** [comment]
Hi @gino-m , Can I take this issue?

**Comment by gino-m** [comment]
> Hi @gino-m , Can I take this issue?

All yours! Please follow up here if you have any questions!

**Comment by parulraheja98** [comment]
Hi @gino-m , I just had a question that can I use the [ngx-color](https://www.google.com) library instead of ngx-color-picker as it seems like ngx-color has inbuilt pickers within it whereas ngx-color-pickup has a very general Sketch type picker. Also can you please clarify the role of icon in this image?

**Comment by gino-m** [comment]
`ngx-color` works as well. It's just a placeholder for our own custom functionality (to add default and recent colors and custom icons) once we have the P0 features implemented.

The icon is used to indicate the currently selected color. We're currently still using the default Google Maps API "pin" markers, so we can use that here as well until we replace them with our own stylized versions.

**Comment by parulraheja98** [comment]
Hi @gino-m , I had a question regarding the implementation. I create a separate component for color-picker and had a question that where would the button go for the trigger of the dialog, would it be in the layer-dialog component or in its own separate component?

Attached is the image for my changes so far:
![image](https://user-images.githubusercontent.com/27938664/73434191-e5f59680-430b-11ea-8a96-99488c76ec13.png)

**Comment by gino-m** [comment]
Good question - the button will live in the layer modal:

![image](https://user-images.githubusercontent.com/228050/73460644-d778a080-4346-11ea-85fb-ed06619488d0.png)

The layer modal is still WIP, so for now you can drop the affordance anywhere inside the dialog component, and we can place it properly in a follow-up. Wdyt?

**Comment by parulraheja98** [comment]
Sounds great @gino-m
