### ISSUE TITLE
Display Terms of Service in app

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1595]
@vittorino Can you please paste in the latest designs? Feel free to replace this description with the designs.

**Comment by jcqli** [comment]
Is this fixed with #1786 ?

**Comment by gino-m** [comment]
> Is this fixed with #1786 ?

Partly. I think there are a few follow-ups required:

- [ ] Replace copyrights with (c) The Ground Authors and link to AUTHORS file in GitHub
- [ ] Load ToS from db and display when clicking Terms of Service; hide link if no ToS present.
- [ ] Require users to accept ToS after signing in if defined in db. 
- [ ] Get recommended final attribution text from team and update

@vittorino Can you provide a quick draft of how we should show ToS, both after sign in for acceptance, and when clicking the menu option?

**Comment by vittorino** [comment]
Terms of service will appear in the help menu on the top bar
![image](https://github.com/user-attachments/assets/5b401ede-2281-4553-b0e2-8047aa1a3feb)

Terms page:
![image](https://github.com/user-attachments/assets/c5aa613f-ebe4-46f0-b2c1-aed8b59c038b)

On Android, all information is grouped under the Terms menu item:
![image](https://github.com/user-attachments/assets/20a16149-5f88-42d0-9488-b80c9ae4599b)

Pages can be accessed through the top tab menu:
![image](https://github.com/user-attachments/assets/78cb01ce-5fa7-47ed-91dc-d367d32fb674)

**Comment by gino-m** [comment]
Thank you @vittorino, great work!

**Comment by gino-m** [comment]
@vittorino Can you also add "I agree" functionality to the web ToS UI, for acceptance after sign in?

**Comment by vittorino** [comment]
Here it is:
![image](https://github.com/user-attachments/assets/97906f9f-f913-463a-82c6-ac5c88721356)

I would suggest to keep the 'Continue' button disabled until the checkbox is selected. Keep in mind this has no alternatives if the user doesn't want to agree. The only exit here would be to sign out.

**Comment by gino-m** [comment]
Discussed with @rfontanarosa, will add a link to the menu "Privacy policy" linking to the Open Foris Ground privacy.

**Comment by gino-m** [comment]
@rfontanarosa @rfontanarosa , could you please work with Vicky to get a version which can be added to the app? Placing a copy of the text in a document in Firestore under "config/tos" in a field called "text" will cause it to appear in the Android app after sign-in.

**Comment by gino-m** [comment]
@amysorto Feel free to use place some Ipsum Lorem text into the dev db for testing.

@rfontanarosa Could you please copy the content in these pages into the ToS in the Open Foris Firestore?

https://openforis.org/ground-terms-of-service/
https://openforis.org/ground-privacy-policy/

**Comment by gino-m** [comment]
@amysorto Let's link to the privacy policy from the ToS instead of copying it, thanks!
