### ISSUE TITLE
[Survey editor] Missing free-form data collection task when toggle is enabled

### ISSUE THREAD

**Issue by jcqli** [google/ground-platform#1606]
**Describe the bug**
When the toggle is enabled, users can still delete the task in the job such that the toggle and the actual job are misaligned.
Toggle: 
![image](https://github.com/google/ground-platform/assets/40325757/01a9f8b5-2274-45fa-b486-1d62c4a419f3)

**To Reproduce**
1. Go to any job
2. Click on the gear settings
3. toggle on the the "Free-form data collection" setting
4. delete the free-form data collection ask from the job

**Expected behavior**
Users should not be able to manually delete the task when the toggle is enabled; they can disable the free-form data collection to remove the task. Temporary solution here is to remove the ability to delete the manually delete the task

**Comment by jcqli** [comment]
@rfontanarosa As discussed with Remi earlier -- is this something you could take on?

**Comment by rfontanarosa** [comment]
already fixed by gino, removing completely the menu when task is an "add loi task"
