### ISSUE TITLE
[Edit survey] Show big scary warning when disabling "free form"

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1620]
Let organizers know users will no longer be able to add LOIs, only select from existing ones! @amegantz for copy when you have a sec. @rfontanarosa FYI. @jcqli for triage.

**Comment by amegantz** [comment]
How about this?

![image](https://github.com/google/ground-platform/assets/112978024/5295432f-e91f-4e82-880d-c00c7a48746b)


Disable new locations?
Data collectors can no longer add new locations for this job. Data will only be collected for existing locations.
[Cancel] [Confirm]

**Comment by gino-m** [comment]
@amegantz s/can no longer/will no longer be able to/?

**Comment by gino-m** [comment]
@amegantz We've been using the term "data collection sites", not "locations".

Suggested title: "Disable free form data collection"
Suggested text: Data collectors will no longer be able to add new sites for this job. Data will only be collected for existing  sites."

**Comment by amegantz** [comment]
![image](https://github.com/user-attachments/assets/120992b2-2cf6-4e72-b191-21f416a47268)

Disable free-form data collection?
Data collectors will no longer be able to add new sites for this job. Data will only be collected for existing sites.
[Cancel [Confirm]
