### ISSUE TITLE
[Create/edit survey] Incorrect spacing between options for "select one" or "select multiple" questions

### ISSUE THREAD

**Issue by jcqli** [google/ground-platform#1626]
**Describe the bug**
The spacing between answer options when creating "select one" or "select multiple" questions is too big

**Current behavior**
![Current spacing between options](https://github.com/google/ground-platform/assets/40325757/0a107efb-b752-46a7-b193-719411a4ef0d)

**Expected behavior**
![Expected spacing between options](https://github.com/google/ground-platform/assets/40325757/2ce92751-c881-488d-a8cd-7a88badb2513)

[Figma link](https://www.figma.com/file/r2uGtyOiWoDa29za7DNuUc/Ground-Acacia-UX?type=design&node-id=4980-5248&mode=design&t=TSH0Bpoq0K0PJoRb-0)

**Comment by gino-m** [comment]
@amysorto PTAL?

**Comment by gino-m** [comment]
Duplicate of #1515
