### ISSUE TITLE
[Create survey] Don't show warnings when deleting options from questions

### ISSUE THREAD

**Issue by jcqli** [google/ground-platform#1654]
**Describe the bug**
In the create survey flow, we should not show a warning about deleting data when removing options from "select one" or "select multiple" questions

![Warning dialog when deleting an option](https://github.com/google/ground-platform/assets/40325757/150ec99b-2216-4639-9ea1-5984b2af6f40)

**Comment by hallsjj08** [comment]
I'd like to work on this issue.

**Comment by gino-m** [comment]
This issue will soon be superseded by #1701. Perhaps you could work on #1672 ?

**Comment by hallsjj08** [comment]
Yeah sure. I'll take a look at that issue.
