### ISSUE TITLE
[Submission list] Show timestamp of submissions

### ISSUE THREAD

**Issue by jcqli** [google/ground-platform#1656]
Currently, only the date is shown on submissions. We should also show timestamps

@vittorino Do you have the mocks for this?

**Comment by rfontanarosa** [comment]
@jcqli @vittorino @gino-m we can show the timestamp as in the submission panel:

<img width="296" alt="Screenshot 2024-09-10 alle 12 52 00" src="https://github.com/user-attachments/assets/d11d28a1-3a99-4834-b517-a3fb55ebe66d">

<img width="285" alt="Screenshot 2024-09-10 alle 12 52 07" src="https://github.com/user-attachments/assets/fc0cf29c-c9b1-42d5-92b8-eedc32e842de">

**Comment by gino-m** [comment]
Do we want to do this, or would it make the list look cluttered? I'd think only showing the data and time submitted in the details card and only the date in the list is ok, but up to @kenstershiro @lecrabe @jo-spek!

**Comment by jo-spek** [comment]
I think it's OK as is, too.

**Comment by gino-m** [comment]
@kenstershiro If you agree please select "Close as not planned" from the menu below:

<img width="324" alt="image" src="https://github.com/user-attachments/assets/3b63ccce-e07e-4a8f-bdaa-d9086820eac8">

**Comment by kenstershiro** [comment]
Agree that it would look cluttered, and we have the timestamp in the details card. Closed.
