### ISSUE TITLE
[Submission list] Panel is blank when job id not found

### ISSUE THREAD

**Issue by jcqli** [google/ground-platform#1657]
**Describe the bug**
When the job ID is not found, the submissions list will be completely empty (e.g., when questions with data are deleted)

example:
![Example of empty submissions list](https://github.com/google/ground-platform/assets/40325757/a3ce86a0-7d6c-4dcd-90ee-03df798a2d52)

**Comment by gino-m** [comment]
@rfontanarosa Punting this to GA
