### ISSUE TITLE
[Submission details] "Other" text breaks submission panel

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1665]
Submission panel still fails on invalid data.

<img width="1728" alt="image" src="https://github.com/google/ground-platform/assets/228050/4284a5cc-5ae0-41d0-bf39-c45a33ec8862">

@rfontanarosa @amysorto @jcqli FYI

**Comment by gino-m** [comment]
@amysorto Could you PTAL?

**Comment by amysorto** [comment]
@gino-m Can you give me access to that survey? I'm trying to reproduce this issue and am unable to

**Comment by gino-m** [comment]
@sufyanAbbasi Can you provide @amysorto with a repro case?

**Comment by gino-m** [comment]
Fixing #1918 should fix this, assigning to @rfontanarosa to confirm.

**Comment by rfontanarosa** [comment]
closed by #1918
