### ISSUE TITLE
[Submission details] Display "other" text along with other option

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1668]
@amysorto @vittorino PTAL?

**Comment by gino-m** [comment]
@rfontanarosa Fixed this, just needs to add "Other: " to indicate the value was an "Other" text.

**Comment by gino-m** [comment]
This appears to still be broken at HEAD:

![image](https://github.com/user-attachments/assets/66f8c6f1-5482-48e4-96c9-f2c0f07ea809)

![image](https://github.com/user-attachments/assets/a6b0bdd4-5202-437e-8d47-3ee537210231)

..and

![image](https://github.com/user-attachments/assets/b17fd6cb-a36c-4421-a683-8406c0fc3658)

![image](https://github.com/user-attachments/assets/83a572b3-9173-4c13-93bb-7a23277d8d75)

**Comment by rfontanarosa** [comment]
![Screenshot 2024-09-03 alle 13 59 51](https://github.com/user-attachments/assets/76a1a8ba-e8db-45ac-a52f-1360ace5a85b)
