### ISSUE TITLE
Submission panel doesn't work when survey switches

### ISSUE THREAD

**Issue by rfontanarosa** [google/ground-platform#1671]
https://github.com/google/ground-platform/assets/10047945/653bcb97-03a0-45e4-b19a-68684f8fba0b

**Comment by gino-m** [comment]
#1695 could help here

**Comment by jcqli** [comment]
@rfontanarosa @gino-m I see the draft PR is from a few months ago, was there a workaround for this?

**Comment by gino-m** [comment]
@rfontanarosa The LOI panel title and list of submissions are also not showing on a normal working when clicking on LOIs in the list:

![Image](https://github.com/user-attachments/assets/b39725dc-e2e0-4811-a701-751f93f4cf3e)

**Comment by chadcook1** [comment]
d
