### ISSUE TITLE
[ACLs] Custom text and link to sign up form not shown when user isn't passlisted

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1679]
See also https://github.com/google/ground-android/issues/2402

@rfontanarosa

**Comment by gino-m** [comment]
Hi @rfontanarosa is this already working on web?

**Comment by rfontanarosa** [comment]
implemented on open foris fork. configuration should be stored into config/properties/signUpUrl

**Comment by gino-m** [comment]
On ground.openforis.org I currently see the following when signing in from a new account:

![Image](https://github.com/user-attachments/assets/0a8caa77-becf-4677-91a2-153451504637)
