### ISSUE TITLE
[Code health] Update `firestore-tools` and `firestore-functions` for local emulation

### ISSUE THREAD

**Issue by sufyanAbbasi** [google/ground-platform#1696]
I'm working end-to-end testing of the platform and app, which requires running the local emulation. I ran into issues with the older version of the `firebase-tools`, e.g.:

https://github.com/firebase/firebase-tools-ui/issues/939

Updating to version `13.1.0` did the trick for me. I also received a warning about `firebase-functions`, would be good to update that one too!

**Comment by gino-m** [comment]
IIrc, I previously had trouble upgrading to 13.1.0 due to transitive deps in the 3P widget we use for drag & drop uploads. The build error in #1697 may be caused by that, but would need to check.
