### ISSUE TITLE
[Code health] Set up end to end testing (local web, mobile, and database emulation)

### ISSUE THREAD

**Issue by sufyanAbbasi** [google/ground-platform#1699]
Mirrors https://github.com/google/ground-android/issues/2420

Formulating an overall strategy to run end to end testing on the mobile and web app. Will need to configure something like Docker or Github Hosted Runners which will spin up a local web server + Selenium WebDriver, local Android emulator + app, and a set up local Firebase database/emulator then run through a set of core tests.

**Comment by gino-m** [comment]
Next steps:

- [ ] Get full flow (web+Android) working on GitHub Actions to size memory and runtime
- [ ] Split into two (web + Android), testing Firestore state in between
- [ ] Add additional test coverage (CUJs and screen rotation)

**Comment by sufyanAbbasi** [comment]
Update: With the submission of #1820, we now have the ability to run three commands in PR comments:

- `/createTest` will run through the survey creation flow
- `/verifyTest` will run through the survey submission verification flow against the `data/test-submit` local snapshot
- `/e2eTest` will run the create test, then pass through data to the ground-android's submit test flow, then will pass that data through to the verify test.
    - Unfortunately, there is still a bug with the emulator that we need to fix up
 
 Next up, we can add testing for other CUJs like offline imagery download, or other Android life cycle consistency triggers like screen rotation.
