### ISSUE TITLE
[Side panel] Long labels should be aligned to top of icon + padding

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1732]
Instead they are center aligned

![image](https://github.com/google/ground-platform/assets/228050/981204a6-c924-46b9-ab54-d2bc665093fb)

**Comment by gino-m** [comment]
@amysorto PTAL?

**Comment by rfontanarosa** [comment]
this is how gmail handle this:

![Screenshot 2024-04-19 alle 15 54 41](https://github.com/google/ground-platform/assets/10047945/ba2d2d76-4173-43f3-a9e2-5b6eb3a85b51)

**Comment by gino-m** [comment]
We can also do that (@vittorino for advice), but this issue was just proposing we top-align the text when it spans multiple lines.
