### ISSUE TITLE
[Task editor] Add "capture location" task by default when creating a new job

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1735]
* Added just after "Add LOI" task if present
* Mark "Required" by default

@rfontanarosa FYI

**Comment by gino-m** [comment]
Hi @hallsjj08, would you like to give this one a go? Is the feature request clear from context, or would you like additional clarification?

**Comment by hallsjj08** [comment]
Yeah, I'll take a look and ping you if I have any questions.

**Comment by hallsjj08** [comment]
I have a few questions about this task.
1. Set required by default -> Can user set it to not required if they want to or should this task always be required?
2. Can this task be deleted or should it be persistent?
3. Can this task be reordered with other tasks or should it remain at the top of the list (i.e. disable dragging/reordering)?

**Comment by gino-m** [comment]
Good Qs, sorry for the delay!

> 1. Set required by default -> Can user set it to not required if they want to or should this task always be required?

Yes, they can, its initial state will be "required", but it an be toggled off to make it optional.

> 2. Can this task be deleted or should it be persistent?

It can be deleted if they want, but they'll usually want to have it so we add it by default.

> 3. Can this task be reordered with other tasks or should it remain at the top of the list (i.e. disable dragging/reordering)?

Yes, it can. It's a normal task in all effects, just gets added automatically.

HTH!
