### ISSUE TITLE
[Feature] Enforce HTTPS on groundplatform.org

### ISSUE THREAD

**Issue by mmisim** [google/ground-platform#174]
Must be done by a repo admin.

Instructions:
https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

Thanks

**Comment by gino-m** [comment]
GitHub doesn't allow me to do this because our domain isn't configured to allow it yet. Following up with SREs and will report back.

**Comment by gino-m** [comment]
I sent out a CL to add the appropriate CAA to our DNS server. Once propagated, we should be able to enable HTTPS on GitHub Pages.

**Comment by gino-m** [comment]
Done. https://groundplatform.org/ is now live.
