### ISSUE TITLE
[ACLs] Don't allow data collectors to see each other's data

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1751]
Requested by @lecrabe

**Comment by jo-spek** [comment]
Jumping in here to highlight that currently data collectors can download the entire job data from the Ground platform. I suppose that data privacy-wise, this could become problematic in the medium term. I vouch for removing the possibility of "Download job data" for data collectors, or to restrict the downloadable data to their own, respectively.

**Comment by gino-m** [comment]
@rfontanarosa FYI. Data collectors shouldn't see the overflow menu on jobs, and the Cloud Function should return 403 called directly.

**Comment by kenstershiro** [comment]
Given @jo-spek 's comment this one feels more urgent to close the access. Let's try to assign it in next iteration

**Comment by kenstershiro** [comment]
@rfontanarosa to check as this may already be fixed

**Comment by rfontanarosa** [comment]
I think it should be closed. wdyt @gino-m ?

at the moment a data collector

- CAN SEE all the predefined lois and all the loi created by them
- CAN EXPORT all their submission related to the predefined lois and to the loi created by them

canExport function returns HttpStatus.FORBIDDEN if the user has no role in the provided survey

![Image](https://github.com/user-attachments/assets/2475b021-a435-458b-bb1e-c1720e4ddcc1)

**Comment by gino-m** [comment]
@rfontanarosa So they don't see data submitted by other data collectors for predefined LOIs unless they're organizers?

**Comment by kenstershiro** [comment]
Answer to above question is yes, so closing as Done
