### ISSUE TITLE
'Publish changes' button when editing a survey is not clickable/interactive

### ISSUE THREAD

**Issue by amysorto** [google/ground-platform#1753]
When trying to reproduce a bug, I was unable to save updates to a survey. This is what the publish changes button looked like:

![image](https://github.com/google/ground-platform/assets/8575252/fc51c797-bffe-41a5-b1c2-22ce7ef4d2f6)

**Comment by gino-m** [comment]
@amysorto What fields did you change in the survey editor?

@rfontanarosa PTAL?

**Comment by rfontanarosa** [comment]
@amysorto what field have been changed? probably there is something invalid in the task editor, is it possible?

**Comment by amysorto** [comment]
@rfontanarosa I was trying to add a multiple choice question, but then I tried change anything and the publish changes button was just not clickable on anything I was trying. I was running it locally but against the live firebase.

**Comment by jcqli** [comment]
Likely a dupe of issue with validation errors, closing
