### ISSUE TITLE
Use protos when exporting to CSV

### ISSUE THREAD

**Issue by jcqli** [google/ground-platform#1779]
Download CSV functions will need be updated to use the new schema. To do this, we can use the shared protos and converter lib being added to lib/ in this project.

Tracked in https://github.com/google/ground-platform/issues/1758

**Comment by jcqli** [comment]
@gino-m Could you add more detail to this?

**Comment by gino-m** [comment]
> @gino-m Could you add more detail to this?

Added to desc.
