### ISSUE TITLE
Stop exporting user emails and names

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1784]

**Comment by jcqli** [comment]
Can be included in protobuf changes

**Comment by gino-m** [comment]
@lecrabe Can you please verify this is what we want to do?

**Comment by gino-m** [comment]
@lecrabe and I chatted. If we don't want survey organizers to see collectors' names and email addresses, removing them from the export is not sufficient; they should also be removed from the web interface, and from the backend database itself. Since some surveys require knowledge of who did what for coordination and validation purposes, forcing anonymous data collection for all surveys is not possible. Instead, we should revisit this if / when we need anonymous data collection, handle it as a survey-level option, and manage the user's data accordingly. 

My suggestion is that we punt on this for now, and ensure that the data sharing consent screens are clear that the data collector's name and email will be shared with the survey organizer.
