### ISSUE TITLE
Data collector can see other's collector's record

### ISSUE THREAD

**Issue by lecrabe** [google/ground-platform#1800]
**Data collector can see other's collector's record**
And they shouldn't

![image](https://github.com/google/ground-platform/assets/13508875/84857aca-4e5d-4bdb-bfeb-cefcccde4dfe)

**Comment by jcqli** [comment]
@lecrabe Are you signed in using the account that created the survey? If so that is working as intended

**Comment by lecrabe** [comment]
no @jcqli I confirm this is with an account that is just data collector, not survey organizer

**Comment by gino-m** [comment]
@rfontanarosa @jcqli Is this issue resolved?

**Comment by jcqli** [comment]
@gino-m I'm not sure, I see a couple PRs were made for this but none mention that this is fixed.

**Comment by gino-m** [comment]
As of yesterday @rfontanarosa said:

> it's half done: submission is missing
