### ISSUE TITLE
Per-survey data sharing agreement in create/edit survey

### ISSUE THREAD

**Issue by jcqli** [google/ground-platform#1856]
Adding agreement information in the create / edit survey flow

Have some multiple choice options or enabling custom text for survey creators to inform collectors of agreement

**Comment by gino-m** [comment]
Detailed FR:

* When creating a survey, survey organizers must select one of the following data sharing agreement options which must be accepted by data collectors before they begin collecting data:
  * Private: Data will be shared with survey organizers only.
  * Public: Survey organizers may share and use data publicly with no constraints (perhaps under [CC0 license](https://creativecommons.org/public-domain/cc0/))
  * Custom agreement: The survey organizer will provide text which the data collector must accept before collecting data.

@vittorino @rawbzz @amegantz for your attention.

**Comment by gino-m** [comment]
@vittorino Could you please paste the designs for changes to create/edit survey flow to allow the organizer to select or specify the data sharing agreement? See latest comment in Figma thread with @rawbzz for details.

**Comment by rawbzz** [comment]
FYI, copy is still WIP

**Comment by amegantz** [comment]
![image](https://github.com/user-attachments/assets/131e728d-a6d1-4920-87fe-9678bff2f07c)
![image](https://github.com/user-attachments/assets/80de73c3-1fdc-4213-b7ba-d4432c121a8d)
PTAL

**Comment by gino-m** [comment]
@amegantz @vittorino This looks great!!! Perhaps it would be helpful to show the survey organizers the exact text the data collectors will see, along with an explanation that that's what they're looking at?

**Comment by vittorino** [comment]
Do you think it's still unclear that the text is what they will see? If so, I would recommend explaining in the instructions rather than simulating a preview because it would be weird if we don't show the same for all 3 options. In my opinion we would be making the UI more complex than what it needs to be.

**Comment by vittorino** [comment]
FYI, small change in the dialog (no horizontal margins) to match the design for mobile:
![image](https://github.com/user-attachments/assets/82cac570-33e2-4bfe-bef8-892541664c78)

**Comment by amegantz** [comment]
> Do you think it's still unclear that the text is what they will see? If so, I would recommend explaining in the instructions rather than simulating a preview because it would be weird if we don't show the same for all 3 options. In my opinion we would be making the UI more complex than what it needs to be.

Like this?
![image](https://github.com/user-attachments/assets/d330be2c-635b-4e9d-b97e-b325c6fc7e42)

**Comment by gino-m** [comment]
@nwkotto Would you like to take this one on?

**Comment by nwkotto** [comment]
Just for reference, this should be a helpful PR to base this off of: https://github.com/google/ground-platform/pull/1190

**Comment by nwkotto** [comment]
Updating the survey proto:
- Add enum for data sharing agreement types
- Include data sharing agreement enum value and custom agreement text values in survey proto

Creating the data-agreement component:
- Create form with data agreement type and custom agreement text fields
- Wire up the template, with mat-cards and mat-radio-buttons, to the component TS file
- Add form level validation to check that if custom is selected, custom text has been entered
- Create output to propagate validation to parent component
- Create input to pass down default type and custom text

Integrating component into create-survey:
- Create dataSharingAgreementToDocument function in proto-model-converter file
- Add new updateDataSharingAgreement method to data-store service
- Add DEFINE_DATA_SHARING_AGREEMENT value to SetupPhase enum
- Integrate new SetupPhase enum into getSetupPhase, setupPhaseToTitle, back, continue, updating the data sharing agreement on save

**Comment by nwkotto** [comment]
Forgot to tag this, but this PR is the next step for this issue: https://github.com/google/ground-platform/pull/1959

**Comment by jcqli** [comment]
Need to add selected option in the survey settings, @vittorino do you have mocks for this?

**Comment by gino-m** [comment]
![image](https://github.com/user-attachments/assets/ffe92c4c-f5e0-4627-9b76-dcff55a9bbf0)

**Comment by jcqli** [comment]
Is this closed with https://github.com/google/ground-platform/pull/1984 now?
