### ISSUE TITLE
[Side panel] Show list of layers

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#188]
Shown when no feature is selected. For now a flat list will do, in the future we'll want to also show the styled marker icon, visibility toggle, and overflow menu. @jacobmclaws is currently creating mocks for the side panel, but functionality/flow will more or less remain the same.

![image](https://user-images.githubusercontent.com/228050/75101603-e7ce1500-55ac-11ea-93a0-0d8e4761ff73.png)

**Comment by gino-m** [comment]
@gyarill Added mock to description. Should we close this now or wait till styling is in for the layers list?

**Comment by gino-m** [comment]
Hi @gyarill can we close this?

**Comment by gyarill** [comment]
well, we do not have a new layer button yet and  menu... btw. what would be inside of menu? An edit button?

Should i add so it pivots to the component that @parulraheja98 created?

**Comment by gino-m** [comment]
Forked into separate issues (see above activity) so closing this for now.
