### ISSUE TITLE
[Project header] In place edit and rename of project title

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#189]
Behaviors, same behavior as in React prototype:

- [ ] Show grey outline on hover
- [ ] Click to show bold color outline and to set focus
- [ ] On Esc, cancel editing
- [ ] On blur or on enter, rename project in db

**Comment by parulraheja98** [comment]
Hi @gino-m , Can I take this issue?

**Comment by gino-m** [comment]
To get started, please make sure you've accepted our CLAs and check out the contents of this Wiki. Kindly send a draft/scrap PR for early comment to make sure we're on the same page. Thanks for contributing!
