### ISSUE TITLE
MultipleChoiceSelection Condition Proto is missing task ID field

### ISSUE THREAD

**Issue by sufyanAbbasi** [google/ground-platform#1899]
Here we define a list of option IDs for selection in the task condition:

https://github.com/google/ground-platform/blob/3581003c6d610b15f0af4dd1313449608d7bc9d7/proto/src/google/ground/v1beta1/job.proto#L245

However, we require a task ID to know whose options they belong to.

The fix is to simply add a `string task_id = 2` field.

**Comment by gino-m** [comment]
@rfontanarosa Is adding converters for the create/edit survey flow now.
