### ISSUE TITLE
[Import GeoJSON] Report cause of import failure to user

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1904]
Currently users only see:
<img width="276" alt="image" src="https://github.com/user-attachments/assets/e41327ab-72af-4636-88a1-eec7cea94c3a">

**Comment by rfontanarosa** [comment]
The error is printed in the console. Maybe we can add "See the console for more details". @gino-m 

```
    } catch (err) {
      console.error(err);
      this.notificationService.error('Importing data collection sites failed');
    }
```
