### ISSUE TITLE
Allow survey organizers to delete LOIs

### ISSUE THREAD

**Issue by lecrabe** [google/ground-platform#1919]
Allow survey organizers to delete LOIs, so that obviously wrong geometries can get cleaned within the platform

**Comment by jo-spek** [comment]
This came up from Servir as well. Early clean-up in the survey makes a lot less effort than later clean-up in the exported data.

**Comment by gino-m** [comment]
Also requested by @n-clinton

**Comment by gino-m** [comment]
Duplicated of #2065
