### ISSUE TITLE
[Project header] User profile popup

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#192]
When clicking avatar/profile pic, show a popup card with the following:

- [ ] Larger profile pic (but no change photo link/icon/affordance)
- [ ] Display name
- [ ] Email address
- [ ] Sign out button

Please use Material Design components. For inspiration while styling:

![image](https://user-images.githubusercontent.com/228050/71561029-20cf8a80-2a3f-11ea-94a9-13933b3bb10f.png)

@jacobmclaws in case you have anything to add on design.

**Comment by gino-m** [comment]
@parulraheja98 would you like take this one on and #218 related to your recent PR #216 ?

**Comment by parulraheja98** [comment]
Hi @gino-m , I would like to take this issue 👍

**Comment by gino-m** [comment]
@parulraheja98 could you kindly make the following UI tweaks to the popup?
- [ ] Center the image
- [ ] Center username
- [ ] Center the signout buttton
- [ ] Use Open Sans font for all text
- [ ] Use material button
  ![image](https://user-images.githubusercontent.com/228050/74872695-c27ea400-532b-11ea-80da-dc99f2eed31c.png)
- [ ] Reduce bottom padding

Current state:
![image](https://user-images.githubusercontent.com/228050/74872613-8c412480-532b-11ea-82b9-e27400d7e387.png)

@jacobmclaws FYI.
