### ISSUE TITLE
[Create/edit survey] UX bug: font-family missing on "or" text

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1947]
<img width="300" alt="image" src="https://github.com/user-attachments/assets/fc78045d-0592-4176-9e31-c45b8f3d372b">

Text appears as the default serif font instead of "Manrope"

@rfontanarosa @os-micmec @vittorino  FYI

**Comment by shashtag** [comment]
Please assign the issue to me.

**Comment by gino-m** [comment]
@shashtag Thanks for taking a look!

**Comment by shashtag** [comment]
Hey @gino-m, I was ale to find this in the code but not on the UI. Please can you help me with the reproduction steps.

**Comment by shashtag** [comment]
Found it.

**Comment by shashtag** [comment]
@gino-m Please help me out with -
- Which font do you want?
- The project does not rebuild and reload on changes. It even does not update when I follow the quick start process after my changes.

**Comment by shashtag** [comment]
@gino-m which font do you want?

**Comment by shashtag** [comment]
@gino-m Whenever I update some code. I am unable to see it's changes on the UI.

**Comment by rfontanarosa** [comment]
closed by https://github.com/google/ground-platform/pull/2007
