### ISSUE TITLE
[LOI Panel] Properties not shown on LOIs with properties

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1956]
Current:

![image](https://github.com/user-attachments/assets/830551c3-addd-4965-858e-38cdb0293f63)

Properties are also not available in the menu, potentially lost during the DB migration?

@rfontanarosa PTAL?

**Comment by jcqli** [comment]
As discussed, filed https://github.com/google/ground-platform/issues/1967 to introduce the widget to the panel. Updated the description above for this bring back LOI properties in its current implementation
