### ISSUE TITLE
[Create/edit survey] Clicking "Publish changes" doesn't bring user back to the main screen 

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1975]
...you currently need to click "Publish changes" followed by "Cancel".

**Comment by rfontanarosa** [comment]
is this issue still valid? @gino-m
what do you think? @kenstershiro

**Comment by gino-m** [comment]
Yes I think so. Otherwise users need to click "Cancel" after "Publish" to return to the main screen, which doesn't feel right. We don't intend for users to click Publish multiple times during the same edit session, so returning to the main page feels correct.
