### ISSUE TITLE
[Dashboard / LOI list] LOI names not shown in list

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#1976]
**Repro**

1. Add LOI via Android app and provide a name
2. Look for LOI in side panel on web app

**Expected**

The name of the LOI should appear

**Actual**

The default label appears instead (e.g., "Unnamed area").

![image](https://github.com/user-attachments/assets/30d25e24-656e-4cac-9822-7dfa2b849dec)

**Details**

Data in Firestore appears correct:

![image](https://github.com/user-attachments/assets/fd997a6e-db50-4dc6-a9b4-937ae3c78cbb)

**Comment by sufyanAbbasi** [comment]
Looks like the properties were not loaded on the LOI, looking into the proto converter function, `loiDocToModel`

**Comment by gino-m** [comment]
Fixed by https://github.com/google/ground-platform/pull/1977
