### ISSUE TITLE
[Data sharing consent] Text on data sharing consent page not unclear

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#2027]
The text should make it clear that the terms define what survey organizers can do with the data... that it's an agreement between the survey organizer and the data collector, _not_ what the system can do with the data. @amegantz PTAL?

**Comment by gino-m** [comment]
There are a few designs with conflicting copy in Figma. Latest from HEAD:

<img width="1481" alt="image" src="https://github.com/user-attachments/assets/5eee9307-be2a-4a45-910c-688edd0ced3c">

A few nits:
- [ ] Consent -> Agreement/Terms: "Consent" is given by data collectors when they agree to the "terms" set by the organizer.
- [ ] Agreement/Terms: Which should we use?
- [ ] Description: We should be explicit that this refers to what terms the data collectors need to agree to regarding what survey organizers can do with their data.
- [ ] Private: Same here.
- [ ] Custom: Something like "Data collectors must agree to the terms defined here:

**Comment by amegantz** [comment]
![image](https://github.com/user-attachments/assets/a5846844-1e48-46e0-90fc-b60cdb548e75)
This is the most up-to-date mock.

**Comment by gino-m** [comment]
Updated list:

- [ ] Consent -> Agreement or Terms: "Consent" is given by data collectors when they agree to the "terms" set by the organizer.
- [ ] "Agreement" or "Terms": Which should we use?
- [ ] Subtitle: "How data should be shared" by whom? Maybe just "Data collectors must agree to these terms before collecting data" would be clearer.
- [ ] Private: "Data will only be shared with survey organizers" makes it seem like we're deciding what the system should do here. Instead, the survey organize is declaring what _they_ will do with the data. In that case, something like "Data collectors give survey organizers to use the data, but  not to shareit with third parties" or something like that.
- [ ] Public: "Data collectors waive all rights to data collected as part of this survey under the CC0 license. Survey organizers may share data freely."
- [ ] Custom: Something like "Data collectors must agree to the terms defined here:"

Wdyt?

**Comment by amegantz** [comment]
I'm ok with using both "agreement" and "terms" to avoid awkward phrases like "agree to the agreement." Might be worth checking with a pCounsel for proper language, as I'm not a lawyer.

How about this?

![image](https://github.com/user-attachments/assets/4a845a37-ee48-41ed-91fd-2ef511850763)
