### ISSUE TITLE
[Header] "Terms of service" and "About" links broken

### ISSUE THREAD

**Issue by jo-spek** [google/ground-platform#2088]
As the title says. On https://ground.openforis.org/signin under the top right "i"-button, the user should be able to navigate to the Terms of service and the About page, but the links don't work.

**Comment by jo-spek** [comment]
Minor bug, probably low priority.

@kenstershiro What priority would you assign? The info are on the OpenForis website anyway and T&C have to be accepted upon registration.

**Comment by kenstershiro** [comment]
@jo-spek P1 seems about right. Given there is some private data like user's location being collected. BTW I'll file a separate ticket on the mobile view of those 2 pages, the content is basically unreadable on my phone screen.

**Comment by rfontanarosa** [comment]
@jo-spek @kenstershiro A previous issue related to newline handling has been fixed (last Thursday).

So, the PR can now proceed with the planned changes:

About link: Visible to all users, including non-logged-in ones.
Terms of Service: Visible only to logged-in users.

**Comment by kenstershiro** [comment]
@jo-spek I created the follow up bug for the mobile viewport here - https://github.com/google/ground-platform/issues/2115
