### ISSUE TITLE
Introduce "Data collector instructions" task

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#2092]
@jabramowitz5 @jo-spek I see organizers have been using job names to provide general instructions to data collectors, which is not the intended us. I would suggest we create a separate "instructions" task, in which organizers can show custom instructions to data collectors.

**Comment by jo-spek** [comment]
Hi @gino-m 
yes, this is a less than perfect work-around, that is unfortunately needed at the moment in the Ghana campaign.
We specifically created the feature requests https://github.com/google/ground-platform/issues/1991 and https://github.com/google/ground-android/issues/2690 for that reason.
We might push those up the priority list a bit?

**Comment by gino-m** [comment]
Thanks! I would perhaps call is something more general, like "Custom  instructions". I'll close this as a duplicate of #1991.
