### ISSUE TITLE
[Submission details] Multiple choice "Other" selection appears as blank

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#2098]
User selected "Other" option appears blank when "Other" option is selected but no "other" text is provided.

![Image](https://github.com/user-attachments/assets/3f0f1063-f84e-4768-be2c-88d4fcd924f6)

Expected:

"Other"

@rfontanarosa @amegantz PTAL?

@jabramowitz5 FYI

**Comment by rfontanarosa** [comment]
closed by https://github.com/google/ground-platform/issues/2099
