### ISSUE TITLE
[Download CSV] "Other" multiple choice values appear as blank

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#2099]
These values appear blank in the exported data when no user text is specified. 

Expected: "Other" or "Other: <user specified text>" (without <>).

@rfontanarosa

**Comment by rfontanarosa** [comment]
this is the db when other text is specified:

![Image](https://github.com/user-attachments/assets/d59c3fa5-2ae6-404a-9d42-7348885e45b6)

this is the db when other text is left blank:

![Image](https://github.com/user-attachments/assets/59e6567c-67a8-4c8b-8aff-372836f3b7d6)

proto doesn't convert otherText:

MultipleChoiceResponses {selectedOptionIds: Array(0), otherText: 'ttt'}
MultipleChoiceResponses {selectedOptionIds: Array(0)}

**Comment by gino-m** [comment]
We should fix this upstream in the Android app (https://github.com/google/ground-android/issues/2846). Once fixed, can we retroactively patch the db by looking for cases where field `7` is specified but empty? This won't help in multiple select (checkbox) cases where >1 value was selected, but we can at least patch the cases where only "other" was selected with no text.

**Comment by rfontanarosa** [comment]
in any case, I think that a change should be done. Let's leave "Other: X" if the value exists, and just "Other" if the value is empty.

in submission view and export csv.

@gino-m wdyt?

**Comment by gino-m** [comment]
> in any case, I think that a change should be done. Let's leave "Other: X" if the value exists, and just "Other" if the value is empty.
> 
> in submission view and export csv.

Yep, that was my suggestion. Does the deserializer give you an empty `MultipleChoiceSelection` object when "Other" is selected but no text specified? Or will you need to add a workaround the proto deserializer?

**Comment by rfontanarosa** [comment]
it gives back an empty object. in theory we should add a workaround in the deserializer but I think it is better to fix it android side. at the moment we have:

```
{
    8:
    [
        {
            2: "taskId",
            7: {}
        }
    ]
}
```

we should have

```
{
    8:
    [
        {
            2: "taskId",
            7: {2: ""}
        }
    ]
}
```

**Comment by rfontanarosa** [comment]
closed by https://github.com/google/ground-platform/issues/2099
