### ISSUE TITLE
[Project header] UI styling of header component

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#214]
Mocks for spacing/placement:
![image](https://user-images.githubusercontent.com/228050/74197574-be68cd00-4c2d-11ea-8ff3-62ded7027487.png)

![image](https://user-images.githubusercontent.com/228050/74197627-cfb1d980-4c2d-11ea-9f22-b7577c44e98e.png)

![image](https://user-images.githubusercontent.com/228050/74197651-dc363200-4c2d-11ea-8fb8-a3d1dcbac0e0.png)

Icon (please scale accordingly):
![image](https://user-images.githubusercontent.com/228050/74197813-17386580-4c2e-11ea-9840-ed0329de8beb.png)

**Comment by parulraheja98** [comment]
Hi @gino-m , I just had a few questions regarding this issue.
First is what is ground in the input box , is it just a fixed text that needs to be displayed as I can see the Tree and Wildlife Project is the title.
Second is where does positioning of Sign in button goes does it goes far right of the screen as in the react prototype?

**Comment by gino-m** [comment]
Yes, "Ground" is fixed text. Sorry I missed the full layout in my previous comment:
![image](https://user-images.githubusercontent.com/228050/74484094-f36f5c80-4e85-11ea-818a-b98e4807c7ae.png)

Thanks to @jacobmclaws and @hintzemichael for the design!

**Comment by gino-m** [comment]
Also done. Rockin' it!!!
