### ISSUE TITLE
[Form editor] Show icons next to each field type

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#22]
Text:  https://materialdesignicons.com/icon/text-short
Number: https://materialdesignicons.com/icon/numeric
Select one: https://materialdesignicons.com/icon/check-circle
Select many: https://materialdesignicons.com/icon/checkbox-multiple-marked

**Comment by parammittal16** [comment]
@gino-m can i work on this ?

**Comment by gino-m** [comment]
@parammittal16 Thanks for your interest! We still need to add a CONTRIBUTING file with the necessary contributors agreement; I'll assign as soon as this is in!

**Comment by gino-m** [comment]
@parammittal16 I've added https://github.com/google/gnd-cloud/blob/master/CONTRIBUTING.md. If you're still interested, could you kindly ping this thread once you've followed the instructions there? Thanks!
