### ISSUE TITLE
[Form editor] Layer modal initialized with single text field

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#224]
If no form is defined, show a single text field with no label. If a label is not specified, the form is not saved.

![image](https://user-images.githubusercontent.com/228050/74902456-2462fc00-5374-11ea-859e-0f315c696192.png)

**Comment by gino-m** [comment]
More details for first PR:
1. When layer dialog is opened, if no form or form fields exist in the layer, add an empty one.
2. Show existing form fields in UI as Material text fields (`elements` sorted by `index`). Refer to https://github.com/google/ground-platform/wiki/Cloud-Firestore-Representation#projects for structure.
3. On save, if label is empty of all form elements is empty, remove the form from the layer before saving.
Wdyt?

**Comment by parulraheja98** [comment]
Awesome , thanks :)

**Comment by gino-m** [comment]
Also note that for now I would just the "Form layout" heading without the descriptive text "Add questions.." since it's not clear what text would be helpful here yet.

**Comment by parulraheja98** [comment]
Awesome :)
