### ISSUE TITLE
[Form editor] Add support for multiple choice fields

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#225]
"Select one" or "select many" field types.

![image](https://user-images.githubusercontent.com/228050/74902591-802d8500-5374-11ea-9af6-369e8784332e.png)

Initialized with single empty option field, allows options to be added/removed/modified. Blank options not

Drag to reorder and image cues will be tracked in separate issues.

**Comment by gino-m** [comment]
To me the spacing of the options feels a bit cramped - I'd recommend indenting the options so that the drag affordance appears aligned with the left side of the question field.

**Comment by gino-m** [comment]
@parulraheja98 Thanks for taking this one! In the first PR feel free ignore the photo, remove option ("x"), and "other" functionality. Those can be added in follow-up PRs linked to this issue. HTH!

**Comment by parulraheja98** [comment]
SGTM :)
