### ISSUE TITLE
[Layer dialog] "Contributors may add" dropdown

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#228]
![image](https://user-images.githubusercontent.com/228050/74903433-ea472980-5376-11ea-8262-54605b954893.png)

Default to only points.

**Comment by gino-m** [comment]
Lines and Polygons can be disabled for now.

**Comment by gino-m** [comment]
@sergeydolgov1 let's discuss this.

**Comment by gino-m** [comment]
@sergeydolgov1 Can you please remind me where we landed on this? Current design look ok?

**Comment by sergeydolgov1** [comment]
@gino-m We discussed that for the MVP pilot we are going to have Points only. 
The checkbox for Points only still makes sense as Project Manager should be able to specify whether they want Collectors to add new points (checked box) or to use only predefined ones (unchecked)

**Comment by gino-m** [comment]
@sergeydolgov1  Sgtm. Let's start with a single checkbox then? How will we surface the idea of "points" to the user? e.g. "Markers", "Points", "Places", etc.?

**Comment by sergeydolgov1** [comment]
> @sergeydolgov1 Sgtm. Let's start with a single checkbox then? How will we surface the idea of "points" to the user? e.g. "Markers", "Points", "Places", etc.?

Do you mean communicating the idea of "points" to Project Managers or Collectors?

**Comment by gino-m** [comment]
Thanks. Yes, I just wanted to verify which word would be shown in the UI.

**Comment by gino-m** [comment]
Postponing to RC1 - @sergeydolgov1 to add FRs to show who added feature (in Android and/or web).

**Comment by gino-m** [comment]
Hi @HemanParbhakar, could you please update the layers dialog in the web UI to reflect this design?
