### ISSUE TITLE
[Project list] Improved "joined project" UX

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#243]
Currently, "+ Join Project" appears above the list of locally cached ("joined") projects, and there is not "leave project option". It's not clear how frequently users will be switching projects, if at all - is this the best way to represent these concepts? How can we make this better?

![Screenshot_1584119125](https://user-images.githubusercontent.com/228050/76643464-72aa8b80-652b-11ea-8611-9f7421fb5607.png)

**Comment by coreyleamon** [comment]
What does "join project" mean? Wouldn't an organizer or facilitator be directly inviting participants? If we think being able to search or browse for citizen projects should be a feature, this link would certainly need extra consideration.

If we anticipate a single user having more than a few projects, my recommendation would be to not house them in a side/nav panel like this. Instead, have a link to projects where they are joined, created, deleted, organized (someone could be a participant in one project, but then be the facilitator in another). We could think about allowing the user to star or bookmark projects which are then accessed easily from this panel (or the dashboard/landing page).

**Comment by shobhitagarwal1612** [comment]
> What does "join project" mean? Wouldn't an organizer or facilitator be directly inviting participants? If we think being able to search or browse for citizen projects should be a feature, this link would certainly need extra consideration.

You're right. Maybe the wording needs to be improved. It's more like loading a project from the list of all projects and saving it locally for offline use.

> If we anticipate a single user having more than a few projects, my recommendation would be to not house them in a side/nav panel like this. Instead, have a link to projects where they are joined, created, deleted, organized (someone could be a participant in one project, but then be the facilitator in another). We could think about allowing the user to star or bookmark projects which are then accessed easily from this panel (or the dashboard/landing page).

The motivation behind adding this UI feature was to display the currently active project. Maybe calling it offline projects would be more UX friendly?

**Comment by gino-m** [comment]
> What does "join project" mean? Wouldn't an organizer or facilitator be directly inviting participants? If we think being able to search or browse for citizen projects should be a feature, this link would certainly need extra consideration.

We do want to support community / crowd sourced projects, which can [eventually] be found by searching, QR code, or project code.

> 
> If we anticipate a single user having more than a few projects, my recommendation would be to not house them in a side/nav panel like this. Instead, have a link to projects where they are joined, created, deleted, organized (someone could be a participant in one project, but then be the facilitator in another). We could think about allowing the user to star or bookmark projects which are then accessed easily from this panel (or the dashboard/landing page).

Based on experience, the vast majority of users will be working on one project. Some may be in 2-3 projects, but I anticipate they will rarely use >3 projects on one device.

Besides what @shobhitagarwal1612 mentioned, "joining" a project" will cause the various features for which data is to be collected to be synchronized in the background when online.

**Comment by gino-m** [comment]
I also would expect the projects to be selectable via a dialog, but it's not clear how to express the difference between "selecting among' projects being synced for offline use" vs "adding a new project to be synced for offline use". A separate entry point for managing these may make sense. Ideas welcome!

**Comment by coreyleamon** [comment]
Hmm — here I am a bit confused by the intent.
To clarify: the intent of this list of projects is to show what has already been downloaded and therefore can be used offline? Or is it the list of projects that should have data downloaded any time there is a connection? Let me know if I'm misunderstanding.

And what is meant by "active" or "inactive" projects? Is that as in, you are part of a project, or you decide to end participation?

If I am understanding the intent, I am not sure that organizing a main navigational structure based on offline or online projects makes as much sense as simply having a list of projects I am a part of, regardless of connection. There should be a way other than navigation to indicate if a project is up-to-date and downloaded, or if it is set to do so when online. I need to understand more here to make a recommendation.

**Comment by gino-m** [comment]
> To clarify: the intent of this list of projects is to show what has already been downloaded and therefore can be used offline? Or is it the list of projects that should have data downloaded any time there is a connection? Let me know if I'm misunderstanding.

For now it's just the former. In the future we would also like to sync project config (forms, layers) and map features for all of these projects either when the app is open or in the background.

> And what is meant by "active" or "inactive" projects? Is that as in, you are part of a project, or you decide to end participation?

"Active" here means the currently selected project (the one you're viewing). Open to suggestions on better/clearer names here.

> If I am understanding the intent, I am not sure that organizing a main navigational structure based on offline or online projects makes as much sense as simply having a list of projects I am a part of, regardless of connection. There should be a way other than navigation to indicate if a project is up-to-date and downloaded, or if it is set to do so when online. I need to understand more here to make a recommendation.

Being a "part" of a project doesn't really have meaning in Ground. Which projects the user has access to is implicit (public projects + projects shared with the user). I agree that which projects are available offline doesn't belong in a main sidenav; we just put it there as a temporary sol'n barring a proper UX design. Let's set some time to discuss?

**Comment by gino-m** [comment]
P.S. This is in the wrong repo - moved to https://github.com/google/ground-android/issues/450
