### ISSUE TITLE
[Top FR] Import point features from CSV

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#252]
Allow features to be added to a layer from CSV. The simplest way to do this would be do add an overflow menu option next to layers in the side panel, "Import points". The CSV would then just need to contain two columns, lat and lng.

**Comment by gino-m** [comment]
@Tiyara FYI. I'll assign once you join our org!

**Comment by Tiyarah** [comment]
I managed to join the project as a Googler. Feel free to assign this issue to me.

**Comment by gino-m** [comment]
Great, very glad to have you on our virtual team!

**Comment by gino-m** [comment]
@sergeydolgov1 FYI, @Tiyarah and I met today to get started on this. Please let us know if you have any changes or questions.
