### ISSUE TITLE
[Layers list] Add overflow menu with "Download CSV"

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#268]
Forked from #188.

**Comment by gino-m** [comment]
The CSV download isn't implemented yet, but we can start adding the link; we'd need the following:
- [ ] Add a link to the layer overflow menu, "Download CSV"
- [ ] Add an icon (Material design CSV or file icon)
- [ ] Add a local config file (`.backend-config.json`?) with `{ cloudFunctionsHost: "some-subdomain.cloudfunctions.net" }`
- [ ] Update web app to build a link to Download CSV using the host in the config file, in the form `https://${cloudFunctionsHost}/exportCsv?p=${projectId}&l=${layerId}`

Wdyt?

**Comment by parulraheja98** [comment]
SGTM @gino-m . 💯
