### ISSUE TITLE
[Docs] Replace "free" with "open source" where appropriate

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#30]
Primarily because, as pointed out by OSI and others, the English word "free" is ambiguous (without cost vs. freedom to do what you want with it), and it carries various connotations due to historical baggage. To remedy this, OSI has come up with a [standard definition](https://opensource.org/osd), and have approved various licenses that meet their standard definition, including Apache 2.0 under which Ground is released.

**Comment by scolsen** [comment]
related: #31

**Comment by scolsen** [comment]
See #35 for a fix. I believe there was only one instance.
