### ISSUE TITLE
[Docs] Update main page tag line

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#31]
From "An open source, map-first data collection platform by global contributors and volunteers at Google." to "Map-first data collection platform for everyone" or similar.

**Comment by scolsen** [comment]
I can take this!

**Comment by scolsen** [comment]
You beat me to it :P Fix #32528433f98fb74407e1f766e6d3008156b09890

**Comment by gino-m** [comment]
Sorry, I forgot I filed this one!
