### ISSUE TITLE
[Layer list] Order of layers changes on each reload

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#310]
This is due to index not being implemented in Layer.

Blocked by #308.

Fyi @gyarill, @parulraheja98

**Comment by gino-m** [comment]
@gyarill Might be fixed, PTAL?

**Comment by gyarill** [comment]
This is already fixed by https://github.com/google/ground-platform/commit/ebea44027a829ae4bc93651102992ad841fd127b isn't it?

**Comment by gino-m** [comment]
> This is already fixed by [ebea440](https://github.com/google/ground-platform/commit/ebea44027a829ae4bc93651102992ad841fd127b) isn't it?

Should be. Thanks for closing!
