### ISSUE TITLE
[Top FR] Show photo thumbnails in observation cards

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#318]
For now, click to download should be sufficient

**Comment by gyarill** [comment]
Gino, could you recommend me a project from gnd-dev database that already have some photos uploaded?

**Comment by gyarill** [comment]
<img width="1429" alt="Screen Shot 2021-04-07 at 11 14 36 AM" src="https://user-images.githubusercontent.com/222107/115773041-d84b8700-a37d-11eb-8e03-fb9881d7c391.png">

**Comment by gino-m** [comment]
@jacobmclaws We were playing with resizing the image to create a thumbnail with max 200x200. Do you have any suggestion on the dimensions and/or treatment of the photo in the UI? 🙏

**Comment by gino-m** [comment]
@DaoyuT Would you like to pick this up where @gyarill left off?
