### ISSUE TITLE
Main page: Font

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#33]
Should we investigate using a specific font for the Ground website? As of right now, the site use the default font, 'Open Sans,' provided by the site theme.

Fonts can have a significant impact on readability and an audience's perception of the platform and what its use-value is.  We may wind up deciding the current font is a-ok—but should we open up a discussion?

Some font resources:

https://fonts.google.com/
https://design.google/library/choosing-web-fonts-beginners-guide/
https://thenextweb.com/dd/2017/03/31/science-behind-fonts-make-feel/

**Comment by scolsen** [comment]
@gino-m fyi

**Comment by gino-m** [comment]
I totally agree. Open to suggestions. One thing that comes to mind is assuming the tool will be used by researchers and academics, a serif font might make sense. [Lora](https://fonts.google.com/specimen/Lora) is a nice one that's also available in Docs, for example. Any other suggestions for body text and title fonts?
