### ISSUE TITLE
[Layer list] Distinguish layers from features in layer list

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#331]
Layers in the layers list now look too similar to features:

![image](https://user-images.githubusercontent.com/228050/84531470-ac1d9f00-acb2-11ea-9df2-26a75c404133.png)

![image](https://user-images.githubusercontent.com/228050/84531479-af188f80-acb2-11ea-9aa5-aa7193469640.png)

We should make it more obvious the list contains layers, not features. @jacobmclaws, @sergeydolgov1. @gyarill FYI.

**Comment by gino-m** [comment]
@jacobmclaws, @sergeydolgov1 what do you recommend we show here instead of the place markers?

**Comment by sergeydolgov1** [comment]
7/7 Update: UXD work in progress

**Comment by gino-m** [comment]
@Mvrs would you like to take this one? :)

**Comment by gino-m** [comment]
Note: Goal is to update layer icon both in layer list and feature panel header.

**Comment by sergeydolgov1** [comment]
@gino-m @Mvrs This is suggested icon style for Layers. We would probably need to also update the icon in the New Layer Modal. 
Would it be possible to automatically match colors of Feature/Point with the color Layer icons (per user selection in the New Layer Modal)? 
Please let me know if you need icon image assets

![image](https://user-images.githubusercontent.com/20148684/90682104-7bb62c00-e232-11ea-8000-01391545b652.png)

![image](https://user-images.githubusercontent.com/20148684/90682013-53c6c880-e232-11ea-9276-0bb4cdde466f.png)

**Comment by Mvrs** [comment]
@sergeydolgov1 it should be possible based on the layer modals. I believe just prefixing the assets according to the selection modal would give back the **matching** color. I would need the icon image assets I believe.

**Comment by gino-m** [comment]
> @sergeydolgov1 it should be possible based on the layer modals. I believe just prefixing the assets according to the selection modal would give back the **matching** color. I would need the icon image assets I believe.

The `MatIcon` component already has a `color` attribute that can be used for adjusting the icon color. The icon itself is part of the standard library. So in the template you might have:
```
<mat-icon aria-hidden="false" aria-label="Layer icon" [color]="iconColor">layers</mat-icon>
```

Then in the component you can expose a `ThemePalette` object with the appropriate color specified.

Wdyt?

**Comment by Mvrs** [comment]
> > @sergeydolgov1 it should be possible based on the layer modals. I believe just prefixing the assets according to the selection modal would give back the **matching** color. I would need the icon image assets I believe.
> 
> The [`MatIcon`](https://material.angular.io/components/icon/api#MatIcon) component already has a `color` attribute that can be used for adjusting the icon color. The layer icon added by Sergey above is part of the standard Angular Material icon set. So in the template you might have:
> 
> ```
> <mat-icon aria-hidden="false" aria-label="Layer icon" [color]="iconColor">layers</mat-icon>
> ```
> 
> Then in the component you can expose an `iconColor: ThemePalette` field with the appropriate color specified.
> 
> Wdyt?

Ah~~~ that sounds more clear

**Comment by gino-m** [comment]
Hi @Mvrs sorry I forgot to assign this one. Please let me know if you accept so I can reassign if necessary. Thanks for taking a look!

**Comment by Mvrs** [comment]
@gino-m no need to reassign. I will update by the end of Sunday if it needs to be.

**Comment by gino-m** [comment]
> @gino-m no need to reassign. I will update by the end of Sunday if it needs to be.

Just checking, thanks so much! 🏅

**Comment by gino-m** [comment]
@gauravchalana1 Would you like to take this one on? For now it just means we'll use the Material layer icon shown above instead of the pin wherever we mean "Layer" and not "Feature", i.e. in the layer list on the right hand panel.
