### ISSUE TITLE
[Layer dialog] When editing Question field, the Return key triggers "Delete" action

### ISSUE THREAD

**Issue by sergeydolgov1** [google/ground-platform#334]
**Describe the bug**
In the "Create New Layer" dialog, when editing Question field, the Return key triggers "Delete" action

**To Reproduce**
1. Go to 'Create New Layer'
2. Type anything in the Question field text
3. Hit Return key
4. See Warning dialog for "Delete Question" action

**Expected behavior**
Return key moves the cursor from "Question" to the text field, i.e. Question type selector

**Screenshots**
![image](https://user-images.githubusercontent.com/20148684/85215097-8898cb00-b328-11ea-8a2c-b6c7ae5c1ef1.png)

**Comment by gino-m** [comment]
@parulraheja98 is working on a fix for this. Thanks for reporting.
