### ISSUE TITLE
[User sign-in] When signing in to Ground in Incognito mode, account sign-in dialog is loading but then quickly disappears 

### ISSUE THREAD

**Issue by sergeydolgov1** [google/ground-platform#336]
**Describe the bug**
When signing in to Ground in Incognito mode, account sign-in dialog is loading but then quickly disappears

**To Reproduce**
1. Sign out of your Ground project
2. Open New Incognito Window in Chrome 
3. Go to your Ground webpage (Need to be signed out)
4. Click on "Sign in" 
5. See that pop-up sign-in window is loading but then quickly disappears, leaving you in the signed out state

**Expected behavior**
Click on the "Sign in" button triggers sign-in window where user can choose their Google account and then sign in

**Comment by gino-m** [comment]
It appears Google sign-in isn't supported in Chrome on iOS:
https://developers.google.com/identity/sign-in/web/troubleshooting#chrome_on_ios_in_incognito_mode

To get it to work, you can enable third-party cookies in Incognito, or sign in using a regular browser tab (non Incognito).
![image](https://user-images.githubusercontent.com/228050/85407342-1a732480-b531-11ea-9f65-9984489d02b6.png)
