### ISSUE TITLE
[Feature details] Update header based on selected feature 

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#344]
Current design:
![image](https://user-images.githubusercontent.com/228050/85618343-a61eab00-b62e-11ea-9b76-2e0b96045601.png)

Some users seeing the demo have been confused when we just show the layer name here. What can we show to let the user know they're seeing details about the selected point/line/polygon? Note that @Tiyarah is adding an import feature that will allow a custom caption to be specified for each feature.

So ideally the heading would reflect that:
* The panel is showing details for the selected point/line/polygon
* The selected feature's caption, if present
* In which layer the feature resides.

For example, the heading could show the custom caption if present, the feature type (Point / Line / Polygon), the feature's Plus Code, and the name of the layer.

@sergeydolgov1 @jacobmclaws for guidance.

**Comment by gino-m** [comment]
@sergeydolgov1 @jacobmclaws cob where did we land with this one?

**Comment by jacobmclaws** [comment]
Ok. So the hard part for me when trying to draw this up is that not all features will have captions, right? So we could do something like put "Point 1" "Point 2" "Polygon 3" or something. We could also ask the user to each feature when they place it? 
Here's a quick mock trying to show some hierarchy. Let me know if this makes sense.
![image](https://user-images.githubusercontent.com/9397366/87766992-ee5b7280-c854-11ea-8ae9-fd334058fceb.png)

To make future examples more realistic and concrete, Gino can you give me an example of a layer name, and a feature caption that one of our pilot programs might have?

**Comment by gino-m** [comment]
> ..not all features will have captions, right? 

Yes, that was my Point as well. (Sorry, I can't help myself). That said, can understand it may be a bit hard to understand which feature a layer belongs to in the current model. Also, @Tiyarah is working on a feature that will allow the captions to be imported in bulk. In that case we may actually want a list. Lastly, in the future if we preload points and want to do crowd-sourced data collection via the web app, we'd need to have a list for users to cycle through.

All that said, @sergeydolgov1 and I spoke today and explored a few approached. He'll provide a more detailed update shortly.

**Comment by sergeydolgov1** [comment]
@gino-m Sharing the latest mocks (see attached)
Suggestion is to keep Layers and Features as Dropdown list but make users select a particular Feature (Point) to see its observations. 
**[Screen 2] User can click on a Feature in the menu OR on the map to see its details/observations**
[Layer-Feature-Observation hierarchy.pdf](https://github.com/google/ground-platform/files/4963877/Layer-Feature-Observation.hierarchy.pdf)

**Comment by gino-m** [comment]
Proposal: Add point icon with (for now) fixed label "Point" below layer header:

![image](https://user-images.githubusercontent.com/228050/90670932-f0cd3580-e221-11ea-9b6a-2bc9bb3ad616.png)

Related to update of layer icon in #331.

@Mvrs would you like to take this one as well?

**Comment by Mvrs** [comment]
@gino-m sure definitively up for it.

**Comment by gino-m** [comment]
Great, thanks @Mvrs. Over to you!

**Comment by gino-m** [comment]
Updated proposal, in several steps:

- [ ] Update feature detail header to show "Point" (if has `location`) or "Polygon" (if has `geoJson`). Just below that show "Layer: _layer name_" in grey smaller font, using similar styles to this:
![image](https://user-images.githubusercontent.com/228050/121407537-6b8c4c00-c92d-11eb-8bf9-069df5e8953a.png)
- [ ] For GeoJSON features, try to guess label from GeoJSON `properties` in GeoJSON using same logic as in https://github.com/google/ground-android/pull/866. First look for `caption`, `label`, `name` ignoring case, if present use that. If not present, use "Point" or "Polygon" + " " + either `id`, `identifier`, or `id_prod`.
