### ISSUE TITLE
[Side panel] Routing from one feature to another does not change contents of side panel

### ISSUE THREAD

**Issue by DaoyuT** [google/ground-platform#373]
**Describe the bug**
Routing from one feature to another changes the side panel, but the color is not correct (still the previous color)

**To Reproduce**
1. Go to home page.
2. Click on a feature.
3. Shows the feature in side panel.
4. Click on a feature from a different layer.
5. Does not show the right color for the marker in side panel.

**Comment by gino-m** [comment]
@gyarill Ok to include in this sprint? 1 unit estimate sound reasonable?
