### ISSUE TITLE
Routing from a feature to primary url does not change the side panel back to list of layers view

### ISSUE THREAD

**Issue by DaoyuT** [google/ground-platform#374]
**Describe the bug**
Routing from a feature to primary url (e.g. http://localhost:4200/p/example)  (deselecting the feature) does not change the side panel back to list of layers view.

**To Reproduce**
1. Go to home page.
2. Shows list of layers in side panel.
3. Click on a feature.
4. Shows details of the feature in side panel.
5. Click on the map to deselect the feature.
6. Still shows the details of that feature in side panel.

**Expected behavior**
Should show the list of layers view in side panel.

**Comment by gino-m** [comment]
Thanks for the bug report!

**Comment by gino-m** [comment]
Likely related to #373.
