### ISSUE TITLE
[Side panel] Tweak style of view/add/edit submissions

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#375]
Please use Angular Material component attributes wherever possible (e.g. `color="primary"`). If necessary, please only update component-level [s]css.

**Comment by gino-m** [comment]
Blocked by #387, #379. I'll fix styling errors and unblock.

**Comment by gino-m** [comment]
@jacobmclaws could you kindly provide feedback on view, add, and, edit observation UIs here? Sharing demo links privately.

**Comment by jacobmclaws** [comment]
SORRY for the long delay. I went to provide feedback on the sidebar this afternoon and the links I had from earlier don't seem to be working (tapping on layers or overflow menu in side panel has no response). Will someone please resend a link? Thanks

**Comment by gino-m** [comment]
Example features in the db were accidentally removed during dev. Shared updated link privately, sorry for the confusion.

**Comment by jacobmclaws** [comment]
Feedback in visual below. Thanks!
![image](https://user-images.githubusercontent.com/9397366/89389895-fc5c2f00-d740-11ea-99d2-ceb14c89e219.png)

**Comment by gino-m** [comment]
Thank you @jacobmclaws, very helpful! Over to you @gyarill!

**Comment by gino-m** [comment]
@gyarill  This came up again during testing. Think you could have a look?

**Comment by gino-m** [comment]
This will be revisited in the future, putting in Icebox for now. @vittorino FYI.
