### ISSUE TITLE
[Layers list] Tap target of three-dot overflow menu incorrect

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#389]
Tap target should be round, centered around icon. It is currently a vertical rectangle stretching down into the next item in the list.

Also, clicking one button multiple times causes others to become highlighted:
![image.png](https://images.zenhubusercontent.com/5f062d0f25250e63f9559a02/caa3573f-0b5a-4837-a31c-da8da890d767)

Please use mat-icon-button instead:
https://material.angular.io/components/button/overview

**Comment by gauravchalana1** [comment]
@gino-m The issue seems to be fixed now as per our conversation. Thank you!
