### ISSUE TITLE
[Dev workflow] Add hook to run Flow type checks on npm run build

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#39]
Described in https://github.com/facebook/create-react-app/issues/5995#issuecomment-446348999

**Comment by bugzpodder** [comment]
This is the only project in google org that uses flow?  I thought google is big on typescript?  Is there any reason why flow is picked over ts?

**Comment by gino-m** [comment]
When I looked into it, it seemed integrating ts with React was non-trivial, and I wanted to minimize the number of custom integrations to reduce complexity. This may have changed since, but since this is a 20%/best-effort project, I haven't had time to investigate this fully.

Also, Ground uses Firebase for db triggers and hosted functions, and the examples in the docs are primarily ES6, so I preferred to use one language across both web client and server-side. ts integration is available, but again, unfortunately I haven't had time to try it out.

**Comment by gino-m** [comment]
Obsolete; will be reimplemented in new version.
