### ISSUE TITLE
[Observation cards] Move "edit" action inside drop down menu behind overflow button

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#394]
![image](https://user-images.githubusercontent.com/228050/87605751-6300a680-c6c7-11ea-956a-104e50d289d1.png)

At present, the overflow button links directly to "edit" mode. Instead, a small menu should appear, for now with one option, "Edit observation". @sergeydolgov1 fyi.

**Comment by sergeydolgov1** [comment]
@gino-m Proposed Menu SGTM. Suggest we also add "Delete observation" action to the same menu. Thoughts?

**Comment by gino-m** [comment]
Agreed. Added details to #70.

**Comment by gino-m** [comment]
@parulraheja98 would you like to take this one on?

**Comment by parulraheja98** [comment]
Thank you @gino-m ,  I will take this task :)
