### ISSUE TITLE
[KML export] Text fields always truncated to first character

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#4]
Example:
![image](https://user-images.githubusercontent.com/228050/48597434-c2734580-e92b-11e8-89be-5a20152991d3.png)

**Comment by gino-m** [comment]
Hi @tiyarah! Would you like to take this one on as a starter project? I'm not sure if it's still occurring, but trying to repo and debugging it will likely make a nice intro to the codebase. Wdyt?

**Comment by Tiyarah** [comment]
Yes I can give it a shot.

**Comment by gino-m** [comment]
@sergeydolgov1 to look into prioritization of KML export. Postponing for now.

**Comment by gino-m** [comment]
Depends on #269.

**Comment by gino-m** [comment]
KML export is not implemented for the current version of the app, so marking this as obsolete.
