### ISSUE TITLE
[Layer model] Default color defined in wrong place in layer object

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#402]
It's currently defined in `color`, it should live in `defaultStyle.color`. Added this to https://github.com/google/ground-platform/wiki/Cloud-Firestore-Representation#projects to clarify.

**Comment by gino-m** [comment]
@parulraheja98 Care to take a stab at this one?

**Comment by parulraheja98** [comment]
Thank you @gino-m  :)

**Comment by gino-m** [comment]
> Thank you @gino-m :)

Thank _you_!
