### ISSUE TITLE
[Jobs] Delete all associated data when deleting a job

### ISSUE THREAD

**Issue by DaoyuT** [google/ground-platform#406]
Deleting the job deletes all the LOIs in that layer. We need to also delete all data collected for that job.feature.

**Comment by gino-m** [comment]
Filed for RC, since from the user's perspective the observations will be gone since there will be no way to access them once the features are removed.

**Comment by gino-m** [comment]
@DaoyuT Is this already implemented in the data store?

**Comment by gino-m** [comment]
I checked the code, it looks like this was already done.
