### ISSUE TITLE
[Home page] Simple list of available projects

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#411]
Add a very simple list of projects available to the current user to be shown when accessing `/projects`.

Target UI (thank you @jacobmclaws):

![image](https://user-images.githubusercontent.com/228050/111510025-b9752780-8723-11eb-83a9-eb8d5dbef45a.png)

The initial version can simply include all projects visible to the logged in user, without "Recent projects", project filter ("All projects"), and sample project. Please let me know if you have any questions!

**Comment by parulraheja98** [comment]
@gino-m Can I work on this next, where should it be placed. I have attached a screenshot for a possibility
![image](https://user-images.githubusercontent.com/27938664/92535483-e983c100-f1fc-11ea-92dd-aee472cdeaff.png)

**Comment by gino-m** [comment]
This would be on a separate page. We don't 100% need this for the pilot, so I'm inclined to leave this out for now.
