### ISSUE TITLE
[Layer list] "Add layer" button missing for new projects

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#412]
Navigate to /p/:new

Note "Add layer" button is missing in right-hand side.

![image](https://user-images.githubusercontent.com/228050/87982903-82bc1400-caa5-11ea-9f46-a812deb0dc52.png)

**Comment by gino-m** [comment]
@gauravchalana1 would you kindly take a look?

**Comment by gauravchalana1** [comment]
@gino-m Sure, on it!

**Comment by gino-m** [comment]
Hi @gauravchalana1 thanks for taking a look!

Are you saying you can't reproduce the issue? If not we can close this issue.

**Comment by gauravchalana1** [comment]
Hi @gino-m , sorry I missed out on your message. 
I am not facing this issue. I think it's good to close. ty

**Comment by gino-m** [comment]
Will do, thanks!
