### ISSUE TITLE
[Delete layer] Update placement and style of delete layer trigger

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#417]
The delete layer button is currently shown directly in the layer dialog:
![image.png](https://images.zenhubusercontent.com/5f062d0f25250e63f9559a02/05b454c4-eb1f-481f-a1e0-ae3213681bfc)

This might be confusing, since there is already a delete button for questions on the dialog.

Also, since this is a highly destructive, yet rarely used feature, it might make sense to put it in a less conspicuous location, reducing the number of always-visible widgets on screen.

@sergeydolgov1 Is it ok to move this behind the overflow menu if the layer list for the reasons I mentioned above

**Comment by Mvrs** [comment]
Hey @gino-m if this one is currently stale can I take a crack at it? Thanks 🙏🏿

**Comment by sergeydolgov1** [comment]
@gino-m @Mvrs Agree to have "Delete" action solely in the Overflow menu in the layer list. Attaching the mock.
Suggested flow: 
1. After clicking on Delete, a dialog appears 
2. Dialog text: "Are you sure that you want to delete this Layer and all associated data?". Dialog Buttons: 1) "Yes, Delete", 2) Cancel
3. After clicking on "Yes, Delete", user is prompted to enter layer name "Please type in Layer name to confirm deletion:"
4. User types in Layer name, hits return and either 1) If Layer name matches see "Layer deleted" or 2) If Layer name doesn't match see "Name that you typed in doesn't match selected Layer, please try again"

**Comment by Mvrs** [comment]
This is ideal. For reasons:
- It prevents layers from unintentional removal 
- It's requires action by the user
- Also, it's more accessible for the layer component.

**Comment by gino-m** [comment]
Thanks @sergeydolgov1 for providing the details, and @Mvrs for taking this one on.

Note that "type layer name to confirm" part isn't required for the first PR - it can be done in a follow-up.

**Comment by gino-m** [comment]
I think this is nice to have for pilot, I'll assign for pilot with lower priority.

**Comment by Mvrs** [comment]
> I think this is nice to have for pilot, I'll assign for pilot with lower priority.

Agree! No worries.
