### ISSUE TITLE
[UX Styling] Update color of relevant icons

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#421]
The UX mocks specify a different color for the delete icon than Angular's default material foreground icon color. 

Default:
![image](https://user-images.githubusercontent.com/228050/88834681-31490e80-d1a2-11ea-83c1-4f5956b73f28.png)

Mocks:
![image](https://user-images.githubusercontent.com/228050/88834735-41f98480-d1a2-11ea-80f8-578f251fa23e.png)

@jacobmclaws, should we update the app theme so that this is the default foreground color for all icons, or is this a special case?

Related to #420 by @gauravchalana1.

**Comment by jacobmclaws** [comment]
I think this black icon, especially when repeated, is too strong and takes too much attention. Since we are using filled icons elsewhere already (as in the filled icon for select multiple in the dropdown) I'm all right with using the filled icon instead of the line art version, but I propose we use the grey color instead of the black. Thanks

**Comment by gauravchalana1** [comment]
@jacobmclaws Sure thing, I will start working on it, also please tag me if you have more comments. Thank you :)

**Comment by gino-m** [comment]
> I think this black icon, especially when repeated, is too strong and takes too much attention. Since we are using filled icons elsewhere already (as in the filled icon for select multiple in the dropdown) I'm all right with using the filled icon instead of the line art version, but I propose we use the grey color instead of the black. Thanks

Thanks Jacob, that makes sense. The main questions I had was whether we should make all filled icons this color, or if this is a special case? If so, is the default Material black ok for those?

**Comment by gino-m** [comment]
Obsolete
