### ISSUE TITLE
[Code health] Rename "RouterService" to "NavigationService"

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#427]
The service is responsible for navigating around the app, not for routing to different components.

**Comment by Mvrs** [comment]
Interesting... can I take this? 🙃

**Comment by gino-m** [comment]
Hi Marlon, sure, please go ahead! Just be sure to follow https://github.com/google/ground-platform/blob/master/CONTRIBUTING.md when contributing. Thanks for offering!
