### ISSUE TITLE
[Feature List] Present features (points) as a list in the menu bar

### ISSUE THREAD

**Issue by sergeydolgov1** [google/ground-platform#443]
1. Features (points) presented as a list in the menu bar, have overflow menu with Edit/ Reposition/ Delete actions 
![image](https://user-images.githubusercontent.com/20148684/90665125-9f20ad00-e219-11ea-8bf4-a6f6a12108d2.png)

2. If user clicks on feature (point) either on the map or in the menu, they see feature menu with all its observations
![image](https://user-images.githubusercontent.com/20148684/90665194-b5c70400-e219-11ea-8d9b-d3016714194d.png)

**Comment by gino-m** [comment]
Obsolete.
