### ISSUE TITLE
ModuleError: Can't find modules 

### ISSUE THREAD

**Issue by Mvrs** [google/ground-platform#455]
**Summary:**
I get the error `Cannot find module './.firebase-config'.` and `'./.google-maps-config'.`

**Steps to Reproduce:**
1. cd into `web-ng`
2. npm run start
3. See error

**Expected Behavior:**
No errors, and display of `http://localhost:4200/ **` successful
I looked into *environment.ts* and it appears the error is producing because I'm lacking an API-key? Possibly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5723692/93555156-08373580-f92a-11ea-8676-e9c3a0aa71c9.png)

**Comment by gino-m** [comment]
Hi @Mvrs, have you followed setup instructions in  https://github.com/google/ground-platform/blob/master/web-ng/README.md ?

Once everything is working, you should be able to create a new Ground project by navigating to http://localhost:4200/p/:new.

**Comment by Mvrs** [comment]
Hey @gino-m, I have it working now but was curious about resolving this issue:

![image](https://user-images.githubusercontent.com/5723692/94071720-43fa5100-fda9-11ea-9c7f-e2cf642be113.png)

**Comment by gino-m** [comment]
Ah, right! We recently added this config file, but we forgot to add instructions for setting it up. Please see revised README.md:
https://github.com/google/ground-platform/blob/master/web-ng/README.md#add-local-environment-config

**Comment by Mvrs** [comment]
> Ah, right! We recently added this config file, but we forgot to add instructions for setting it up. Please see revised README.md:
> https://github.com/google/ground-platform/blob/master/web-ng/README.md#add-local-environment-config

I knew something was missing haha. Thanks!
