### ISSUE TITLE
[Layer dialog] Tweak line spacing and padding for “Form layout” and “Add question..” description

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#472]

**Comment by gino-m** [comment]
![image](https://user-images.githubusercontent.com/228050/98122085-1ca1a400-1e7e-11eb-88e9-98d9c5ca2748.png)

**Comment by gino-m** [comment]
Hi @gauravchalana1 care to take a look?

**Comment by gauravchalana1** [comment]
Hi @gino-m yes, I have started working on them
