### ISSUE TITLE
[Profile icon] Change to clickable UI component

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#489]
Hovering over the profile pic in the top-right corner doesn't turn the cursor to a hand icon and doesn't show Material visual tap feedback when clicked. This can be resolved by rendering the icon using a clickable component, possibly mat-button.

**Comment by DakshSaini** [comment]
Hi @gino-m, can I work on this issue? Thanks.

**Comment by gino-m** [comment]
Certainly! Reassigning to you now. Please be sure to follow instructions on CONTRIBUTING.md before submitting your first PR. Excited to receive your contribution!
