### ISSUE TITLE
[Docs] Assets do not load from custom domain

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#49]
We recently acquired and configured vanity URL groundplatform.org. When setting the custom domain in GitHub Pages Settings, assets are not found because URLs include /ground-platform prefix, which doesn't work from custom domain. I believe to fix this we need to specify a base url in _config.yml and to update the page sources as per:
https://github.com/jekyll/jekyll/issues/332#issuecomment-18952908

**Comment by scolsen** [comment]
This can be closed now, I believe! 💯 groundplatform.org
