### ISSUE TITLE
[Edit survey] Show modal progress spinner while deleting job

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#527]
Delete layer was introduced in the layer dialog in #386. The UI is still active while features are being deleted, leading to potential race conditions.

**Comment by DaoyuT** [comment]
@gino-m Is this out of date or a duplicate of #1409 ?

**Comment by gino-m** [comment]
@DaoyuT I don't think we block while deleting a job, in which case this is still needed

**Comment by gino-m** [comment]
Merging with #1396
