### ISSUE TITLE
[Import CSV] Show upload progress and success/error message

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#528]

**Comment by parulraheja98** [comment]
@jacobmclaws , Can you please suggest the mock UI for this state. @gino-m  FYI

Relavant screenshots:

Error of CSV upload:

<img width="804" alt="Screen Shot 2021-04-28 at 8 42 42 PM" src="https://user-images.githubusercontent.com/27938664/116492603-4a323d80-a862-11eb-892a-fa0844ed475c.png">

Success of CSV upload:

<img width="802" alt="Screen Shot 2021-04-28 at 8 43 09 PM" src="https://user-images.githubusercontent.com/27938664/116492618-59b18680-a862-11eb-9e21-879cae23e797.png">

Loading state:
![spinner-1](https://user-images.githubusercontent.com/27938664/116494864-5a98e700-a867-11eb-93d1-cfe9958ab8a3.gif)

**Comment by gino-m** [comment]
@jacobmclaws Any chance you could provide guidance on the import success/failure toast and progress bar shown in @parulraheja98 's screenshots above? 🙏
