### ISSUE TITLE
[Code Health] Set up linting

### ISSUE THREAD

**Issue by dhvogel** [google/ground-platform#58]
People who contribute to this project may have differing code style norms. We should add linting rules to enforce consistent norms around code aesthetics. Ideally, these linting checks would be run on presubmit (PR opening) by some continuous integration tool.

eslint-plugin-react looks like a good option: https://github.com/yannickcr/eslint-plugin-react

**Comment by gino-m** [comment]
+1. Is this something you mind be interested in helping set up?

**Comment by gino-m** [comment]
I noticed some files are using tabs and others spaces. Can we update our linter to enforce [two-space indent](https://google.github.io/styleguide/jsguide.html#formatting-block-indentation)? @gyarill FYI.

Or even better, would https://github.com/google/eslint-config-google work with React as well?

**Comment by dhvogel** [comment]
Added google standard config in #65
