### ISSUE TITLE
[Project title] On new project, prompt for title in modal dialog

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#581]
When navigating the /:new, a title must be specified via a non-dismissible modal dialog before the user may proceed. The UI will be come active only once the project has been saved.

Fixes #580.

**Comment by gino-m** [comment]
@gauravchalana1 @DakshSaini @parulraheja98 @DaoyuT @gyarill Anyone interested in this one?

**Comment by DakshSaini** [comment]
> @gauravchalana1 @DakshSaini @parulraheja98 @DaoyuT @gyarill Anyone interested in this one?

@gino-m I would like to give it a go?

**Comment by gino-m** [comment]
All yours! If possible in general please handle highest priority bugs first. Thanks for taking this one on!
