### ISSUE TITLE
[Code health] Refactor override of Material component fonts

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#604]
We currently define fonts for each individual component (e.g., `<button mat-button..`). Instead, we can follow https://material.angular.io/guide/typography to override fonts globally.

**Comment by twopill** [comment]
@gino-m Hey,  Could I try to refactor it?

The code refactor is: remove all css property for the font and implement typography with material, true?

**Comment by gino-m** [comment]
@twopill Yep, that's correct. Please go ahead! Would you like to try to refactor a single instance to start just to make sure we're on the same page?

Please be sure to accept the CLA at https://cla.developers.google.com/ before sending the PR.

**Comment by twopill** [comment]
@gino-m Yes sure!
Thanks i have accepted the CLA.

**Comment by twopill** [comment]
@gino-m I have a problem with the project.

I configure all enviroment files need for work and setup the firebase.

But when i navigate to http://localhost:4200/project/firebase project id name

I have this in console:

`core.js:4610 ERROR FirebaseError: 
Null value error. for 'get' @ L108, Null value error. for 'get' @ L109, Null value error. for 'get' @ L110`

So i try to creare new project, in http://localhost:4200/project/new

And after navigate the page show me the input text, but in console:

`You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started`

So i try to insert the name of the project.. but after 3 200 in http://localhost:8080/google.firestore.v1 

Nothing.

**Comment by gino-m** [comment]
Hi @twopill, so sorry for the delay, I was out the past few days.

The error you posted seems related to the Maps API, but I'm not sure that's the cause of this issue. 

Are you on Discord by chance? Please ping me (gino-m) and I'll get in touch there.

@DaoyuT Would you be able to help diagnose?

**Comment by twopill** [comment]
> > @gino-m I have a problem with the setup project.
> > I configure all enviroment files need for work and setup the firebase.
> > But when i navigate to http://localhost:4200/project/firebase project id name
> > I have this in console:
> > `core.js:4610 ERROR FirebaseError: Null value error. for 'get' @ L108, Null value error. for 'get' @ L109, Null value error. for 'get' @ L110`
> > So i try to creare new project, in http://localhost:4200/project/new
> > And after go to the page, it show me the input text, but in console:
> > `You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started`
> > So i try to insert the name of the project.. but after three xhr 200 to: http://localhost:8080/google.firestore.v1
> > Nothing.
> 
> Maybe give it a try with the [added commands](https://github.com/google/ground-platform/commit/e4c710a24175021f60af38524ce3b0aaea7d37bf). Guessing billing can't be required for using emulators

Nothing, the same problem:

<details>
<summary>
Imagine Preview
</summary>

![image](https://user-images.githubusercontent.com/58731523/137553909-dac8da06-f0f8-4ce6-aff7-061363c8222e.png)

</details>

**Comment by gino-m** [comment]
Hi @twopill, sorry you're having trouble. I checked out a fresh clone and wasn't able to get the emulator running locally either. For starters, it appears Firebase requires an actual project be set even when running locally (https://firebase.google.com/docs/emulator-suite/connect_and_prototype). Also, I'm wondering if we can work around needing .config files to be created for local development. I'll try to set some time aside Sunday eve to look into making this easier for new developers. In the meantime, are you able to run against a real Firebase instance?

Note that the "Billing" warning is likely related to your Google Maps API key.

**Comment by gino-m** [comment]
@twopill hi again! If you'd like to run in a local emulator without a live Firebase project you should now be able to do so; just pull the latest and follow the "Quick start" instructions in `README.md` in the repo root. Please let me know if it works or if you have any questions!

**Comment by gino-m** [comment]
> Ok @gino-m , in this days i try it.
> Thanks a lot of for the help !

My pleasure. To see how the app behaves when hosted you would still need to create a Firebase project. It's easy to do, but if you'd like to just make a small change without creating and configuring a project, the local approach should work. Please let us know how it goes!

**Comment by twopill** [comment]
@gino-m I tried to re install all... and it worked:

![image](https://user-images.githubusercontent.com/58731523/139589323-31b97a01-3e76-459e-8c0d-d323719c4b2f.png)

**Comment by gino-m** [comment]
> @gino-m I tried to re install all... and it worked:
> 
> ![image](https://user-images.githubusercontent.com/58731523/139589323-31b97a01-3e76-459e-8c0d-d323719c4b2f.png)

Evviva! 😄  Glad it's working now!
