### ISSUE TITLE
[Router] Refactor calls to Router navigate() into NavigationService

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#605]
Classes should never call router.navigate() directly; instead, we should encapsulate these calls in NavigationService. For example:

```ts
  this.navigationService.signIn();
  this.navigationService.newProject();
  this.navigationService.selectProject(projectId);
  // etc..
```

@DakshSaini FYI

**Comment by gino-m** [comment]
@DakshSaini Would you like to take this one, as it's a continuation of your previous work?

**Comment by DakshSaini** [comment]
> @DakshSaini Would you like to take this one, as it's a continuation of your previous work?

100%, I'll work on this next.
