### ISSUE TITLE
[ACLs]  Hide "Edit submission" when appropriate

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#615]
Hide link in menu if user is not an owner, manager, or the creator of the observation

Implement `AuthManager.canEditObservation(Observation)` to support this. The method will always return if the user is `manager` or `owner` of the project, and false if the user is `viewer`. If the user is `contributor`, returns true iff the logged in user is the creator of the observation (as determined by `auditInfo`).

@gauravchalana1 Would you to take this one?

**Comment by gauravchalana1** [comment]
Hey @gino-m , sure thing! I will work on this 😊

**Comment by gino-m** [comment]
Obsolete; add/edit flow TBD.
