### ISSUE TITLE
[Code health] Rename NavigationService files

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#622]
The class and tests are currently defined in `web-ng/src/app/services/router/router.service.*`. The `router/router.service.*` should be renamed to `navigation/navigation.service.*`.

@gauravchalana1  @DakshSaini @parulraheja98 interested in this one? Reply here if yes!

**Comment by DakshSaini** [comment]
@gino-m, can I take this one? 😃

**Comment by gino-m** [comment]
Please do!
