### ISSUE TITLE
"Add Layer" button in side panel does not show up after creating a new project

### ISSUE THREAD

**Issue by DaoyuT** [google/ground-platform#633]
**Describe the bug**

After creating project, the "Add Layer" button in side panel does not show up. It shows up then after refreshing the page.

**To Reproduce**
1. Create a new page
2. The "Add Layer" button in side panel does not show up
3. Refresh the page
4. The button shows up now.

**Caveat**
This only happened to Heman when the map api fails on him. This did not happen to my local environment. So consider this as very low priority task.

**Screenshots**
![Screen Shot 2021-03-25 at 2 02 46 PM](https://user-images.githubusercontent.com/10445677/112522553-287dfc00-8d74-11eb-85c1-74ba6346272f.png)

**Comment by gino-m** [comment]
I haven't been able to reproduce this. @HemanParbhakar is this still an issue?
