### ISSUE TITLE
[Dev Workflow] Add Issue/PR templates

### ISSUE THREAD

**Issue by dhvogel** [google/ground-platform#64]
Issue/PR templates can help make Issues/PRs more readable by standardizing the way contributors report problems and describe solutions.

Open source projects such as golang have them: https://github.com/golang/go/tree/master/.github

I have used a simplified issue template to more or less talk to myself in personal projects: https://github.com/dhvogel/cryptorides-karl/blob/master/.github/ISSUE_TEMPLATE.md

here are some other templates we can chose from: https://github.com/stevemao/github-issue-templates

**Comment by gino-m** [comment]
Done!
