### ISSUE TITLE
[Feature panel] Edit observation flow

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#67]
User selects a map feature and clicks "Edit" in the overflow menu on an existing record in the side panel to allow editing of existing record data.

@hintzemichael Could you please also paste mocks for this one? The design should be mostly identical to #10.

**Comment by gino-m** [comment]
Hi @hintzemichael! If you have an early draft that would work as well. Thanks for the support!

**Comment by dhvogel** [comment]
Assuming that [this](https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZb2iviPIZTOF/files/MCEJu8Y2hyDScSOUrSBm4_v8gCZK1S-lZ5Q) is the mock.

My assumption is that the "edit record" behavior is a drop down from the three vertically aligned dots in the top right of each record card. Please confirm that this is the desired behavior.

**Comment by gino-m** [comment]
That's correct. You would edit one observation (record) at a time. Mock of view-mode for reference:
![image](https://user-images.githubusercontent.com/228050/64058809-ca306d80-cb7e-11e9-8355-83861102068b.png)

As far as UX design please use MD2 standard widgets and your best judgement. We're using the [Outlined](https://material-ui.com/components/text-fields/#outlined) input box style in the Android app so may be best to use that here too for consistency. Thanks a million!
