### ISSUE TITLE
[Form editor] Can't drag to highlight text in form editor

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#677]
Cursor drags (e.g., on question and options labels), are interpreted as form field drags. The drag target should be limited to the "=" handle and surrounding area at the top of the question field.

@gyarill Could you PTAL? 🙏

**Comment by gyarill** [comment]
So according to documentation https://material.angular.io/cdk/drag-drop/overview#customizing-the-drag-area-using-a-handle "By default, the user can drag the entire cdkDrag element to move it around. If you want to restrict the user to only be able to do so using a handle element, you can do it by adding the cdkDragHandle directive to an element inside of cdkDrag"

We do have cdkDragHandle inside of cdkDrag so i am not sure why it is not working...

I see that they had issues over years connected to that e.g. https://github.com/angular/components/issues/13653, https://github.com/angular/components/issues/13335 but they are closed

**Comment by gino-m** [comment]
Hi @gyarill, since this isn't blocking the field work I'll come back to it to take a look once all the blockers are completed. Thanks for the initial investigation!
