### ISSUE TITLE
[Feature panel] Delete observation flow

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#70]
Only record creator and project managers should be allowed to delete records. 

@hintzemichael should this be added to the overflow menu on records in the side panel?

**Comment by ucalyptus** [comment]
@gino-m  Since it's a good-first issue. Should deletion be allowed ? what is the status of this issue rn?

**Comment by gino-m** [comment]
> @gino-m Since it's a good-first issue. Should deletion be allowed ? what is the status of this issue rn?

Hi @ucalyptus this is still required, but we're currently regrouping and reprioritizing so we aren't accepting PRs for the next week or two. I'll update this bug once we have clarity on our next steps!

**Comment by gino-m** [comment]
@gauravchalana1 fyi, this would be surfaced as a "Delete observation" option behind the overflow menu (three dots) shown on observation cards:
![image](https://user-images.githubusercontent.com/228050/87965907-7bd3d800-ca8a-11ea-8e71-844588faad1b.png)
