### ISSUE TITLE
[Layers] Use default marker color in project config

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#71]
Markers currently get added to the map here:
https://github.com/google/ground-platform/blob/d1fa1bbdb188a3e74a9bd8edb34a65c9cb6a7672/web/src/components/gnd-map/index.js#L64-L70

We can add the default color to a new object, `defaultStyles` defined inside `project.featureTypes`. Since we don't have a UI for defining these yet, you can add them manually via the project json editor by clicking `<>` next to the project title in the web UI, e.g.:

![image](https://user-images.githubusercontent.com/228050/60023088-17fe9600-9663-11e9-83b2-ef0be3854439.png)

The color can then be read in the above function with something like `project.featureTypes[featureId].defaultStyle.color` (minding missing/undefined instances).

**Comment by DaoyuT** [comment]
PR#100 merged
