### ISSUE TITLE
[Delete feature] Delete feature option gone

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#711]
Introduced in #451. Can we add this back to the overflow menu? 

@jacobmclaws Did you have mocks for this?

**Comment by gino-m** [comment]
@DaoyuT Would it be possible to revive this? A temporary treatment would be fine until we get mocks. @jacobmclaws Gentle ping.

**Comment by DaoyuT** [comment]
Hi @jacobmclaws, I have uploaded a screenshot in the PR above. Let me know what you think about the look. I'll be happy to change it.
