### ISSUE TITLE
Implement new survey list UI

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#72]
Allows users to select a project or add a new one. Main entry point to app, similar to Docs, Sheets, etc.

**Comment by sergeydolgov1** [comment]
Latest UX suggestion:
A) For new users without existing/recent projects
![image](https://user-images.githubusercontent.com/20148684/86859914-a5e3ce00-c078-11ea-86e7-64942b188424.png)

**Comment by sergeydolgov1** [comment]
Latest UX suggestion:
B) For new users **with** existing/recent projects
![image](https://user-images.githubusercontent.com/20148684/86859962-bdbb5200-c078-11ea-85aa-d172e78e0ee6.png)

**Comment by gino-m** [comment]
A few questions:

"See sample project" implies there's only one that is shared with everyone; I assume this isn't the case? Should clicking create a new project using a template, or something else?

Does the "Recent projects" show all projects opened in reverse chronological order?

What does the "All projects" drop down do, and what options appear there?

**Comment by gino-m** [comment]
@sergeydolgov1 I assume for pilots we can direct users to a specific URL, in which case we can work around the missing landing page? Please cmiiw.

**Comment by sergeydolgov1** [comment]
> @sergeydolgov1 I assume for pilots we can direct users to a specific URL, in which case we can work around the missing landing page? Please cmiiw.

@gino-m Agree, for pilots we can use URLs, landing (starting) page is not required. 

Ideally, it would be good to have URLs of all created projects visible somewhere so that Project Manager can easily switch between them (e.g. a simple dialog with all Project links behind main Overflow button), LMWYT

**Comment by gino-m** [comment]
Sgtm. Added #411 to add a simple list for now.

**Comment by gino-m** [comment]
Closing due to staleness. Will open a new issue for the new experience.
