### ISSUE TITLE
[Terra Bio] Triple dot header menu doesn't do anything?

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#733]
**Describe the bug**
Clicking the triple dot (snowman) menu in the platform app's header appears to have no effect.

https://user-images.githubusercontent.com/11237600/120382581-ce5c6280-c2f1-11eb-8362-fa1df3c32224.mov

**To Reproduce**
1.  Sign in to ground
2. Click on the triple dot menu in the header
3. Nothing happens.

**Expected behavior**
Some kind of menu pops up?

**Comment by coreyleamon** [comment]
Confirmed for me as well

**Comment by gino-m** [comment]
This is reserved for future use, but probably should be removed until needed. Thanks for filing.
