### ISSUE TITLE
[CRITICAL] CTA to add data point/poly is missing

### ISSUE THREAD

**Issue by coreyleamon** [google/ground-platform#734]
**Describe the bug**
On Android version 8.0.0

When I log in as a non-owner on my personal android device, I am able to join a project but not add a data point. The CTA to add a data point is missing from the screen.

**To Reproduce**
1. Create test project in web as owner
2. Log in on android as non-owner and choose test project
3. CTA missing

**Expected behavior**
![iPhone 8 - 1](https://user-images.githubusercontent.com/22535879/120382994-2c308080-c2d9-11eb-9ff9-22d06a4c213a.png)

**Screenshots**
![Screenshot_20210601-144516_Ground](https://user-images.githubusercontent.com/22535879/120383014-318dcb00-c2d9-11eb-836e-797665334ea4.jpg)

**Comment by gino-m** [comment]
Hi @coreyleamon, does at least one of the layers in your project have "Contributors may add points" selected?

**Comment by coreyleamon** [comment]
Ah, I had to sign out and sign back in. Not ideal but can be included with training.

**Comment by gino-m** [comment]
Related to https://github.com/google/ground-android/issues/21, which should resolve the reloading issue.
