### ISSUE TITLE
[Add/Edit Observation] Unclear when layers have no tasks

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#735]
**Describe the bug**
When a layer has no questions assigned to it, the **Add Observation** button won't be rendered, but there's no message detailing why one can't add an observation to the layer.

<img width="1900" alt="Screen Shot 2021-06-01 at 4 03 17 PM" src="https://user-images.githubusercontent.com/11237600/120383652-22b41200-c2f3-11eb-8d3d-26c98b06eca3.png">

**To Reproduce**
1. Add a layer with no questions
2. Import features for the layer
3. Select a feature

**Comment by gino-m** [comment]
Perhaps we should say something like:

> Observations not allowed for features in layer _X_; no observation form defined for this layer.

@mmisim @jacobmclaws  Do you think that's clear?

**Comment by mmisim** [comment]
I would try to keep consistency with the text for layers that have questions and avoid "not allowed" since it might be interpreted as an access issue. I would also emphasize what the user needs to do in order to add observations. What about something like:

> No observations found for the selected feature. To add observations, add a question in the **Customize layer** window for _layer name_.

**Comment by gino-m** [comment]
Good point, I like the suggested text much better for project managers, but contributors won't have access to Customer layer. In that case what could we show?

**Comment by mmisim** [comment]
Ah right. Unless there's any harm in exposing the instructions to all roles, I would just be explicit about which roles can customize layers, especially since space/character count isn't a concern here. What about:

> No observations found for the selected feature. 
>
> To add observations, create a question in the **Customize layer** window for _layer name_. Note that only project owners and managers can customize layers.

While it's not the most helpful thing to tell contributors and viewers about a feature that they can't access, the alternative is to just tell them that the layer doesn't have any questions without providing any indication of how to fix it. At least this way they could tell the project owner what they need to do.

**Comment by gino-m** [comment]
I'm not a big fan of the idea of exposing features only accessible to the project manager to contributors. It's extra work for them to understand the text doesn't actually apply to them, and makes the application seem more complex than it actually is from their perspective.

What if we give layers with forms a different treatment altogether? We were planning to expand feature details panel header to include a user-defined caption, ID, custom properties, Plus Code, etc. What if we just design it in such a way that the user won't miss the observations if they're not allowed there? @jacobmclaws for UX design input.

**Comment by gino-m** [comment]
Not supported in new UI
