### ISSUE TITLE
[Add Observation] Observations won't save

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#740]
Added observations aren't saving for a layers with imported GeoJSON features:

https://user-images.githubusercontent.com/11237600/120384573-5479a880-c2f4-11eb-846c-89d88e3e712a.mov

**Comment by scolsen** [comment]
@gino-m since this seems potentially problematic

**Comment by gino-m** [comment]
That definitely doesn't look right! @gyarill could you ptal? 🙏

**Comment by gino-m** [comment]
Let's close for now and reopen if it happens again.
