### ISSUE TITLE
[Import] Make it clear which file extenstions are supported for import

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#741]
Currently, there's no indication within the app itself as to what file formats are supported for importing features. The file selection dialog currently permits selecting files of any type, resulting in immediate failure on selection of an unsupported format.

https://user-images.githubusercontent.com/11237600/120385518-88090280-c2f5-11eb-8b6e-06618ddd107e.mov

**Comment by gino-m** [comment]
Currently .geojson and .csv are supported.

**Comment by gino-m** [comment]
- [ ] Ideally filter by *.csv and *.geojson 
- [ ] Show text below title "Select a CSV or GeoJSON file to upload"

**Comment by gino-m** [comment]
Related to #1528

**Comment by gino-m** [comment]
@jcqli Removing from past iteration until we can reschedule.
