### ISSUE TITLE
[Add/Edit Observation] Unclear which form fields are required

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#743]
**Describe the bug**
Currently, our only visual indication that a required form field is not filled in is disabling the "Save" button. But this doesn't tell the user which fields are required (so she can do the minimum amount of work).

<img width="316" alt="Screen Shot 2021-06-01 at 4 26 55 PM" src="https://user-images.githubusercontent.com/11237600/120386289-72480d00-c2f6-11eb-941c-cbe158a26792.png">

**Comment by gino-m** [comment]
Show "*" after question for required fields. @parulraheja98 PTAL?

**Comment by gino-m** [comment]
@parulraheja98 We discussed, this is in queue after #788.
