### ISSUE TITLE
[Add/Edit Observation] Save observation button doesn't work for layers on which contributors can't add points

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#744]
**Describe the bug**
The add+save observation flow is janky/broken when attempting to add an observation (signed in as owner) to a layer on which contributors cannot add points:

https://user-images.githubusercontent.com/11237600/120387126-83454e00-c2f7-11eb-8032-4712b2de21ca.mov

**Comment by gino-m** [comment]
Whether the user can add points is orthogonal to whether they can add observations. @gyarill Could you PTAL? 🙏

**Comment by gino-m** [comment]
Obsolete
