### ISSUE TITLE
Users aren't routed to a project after signing into Ground for the first time

### ISSUE THREAD

**Issue by mmisim** [google/ground-platform#760]
**Describe the bug**
If you share a project URL with a new Ground user who has never signed into that Ground instance, they are prompted to sign in. However, after signing in, they are routed to `https://<Firebase project ID>.web.app/project/new`, instead of `https://<Firebase project ID>.web.app/project/<Ground project ID>`. This makes difficult to share projects because they may think that they need to create a project after signing in.

**To Reproduce**
1. Add a user to the passlist in Firebase.
2. Add the user as collaborator in the web app.
3. Copy the web app project URL, e.g. `https://<Firebase project ID>.web.app/project/<Ground project ID>`.
4. Share the project URL with the collaborator and have them sign in.

**Expected behavior**
After signing in, the user should be routed back to `https://<Firebase project ID>.web.app/project/<Ground project ID>`.

**Comment by gino-m** [comment]
Users are now routed to the survey list.
