### ISSUE TITLE
[Photos] Photos are resized, original not accessible to user

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#761]
@shobhitagarwal1612 Any idea why this might be happening? Is the Android app resizing them before uploading?

**Comment by shobhitagarwal1612** [comment]
The bitmap we receive from the activity result is already compressed. I'll also give this a try.

**Comment by gino-m** [comment]
> The bitmap we receive from the activity result is already compressed. I'll also give this a try.

Compression is expected, but we're seeing the images resized to a lower resolution. Please let me know what you find!

**Comment by gino-m** [comment]
Perhaps we're only saving the thumbnail?

**Comment by shobhitagarwal1612** [comment]
That might explain why image selected from gallery are fine but clicked using camera are low res.

**Comment by gino-m** [comment]
Yep, I think that's the problem. 

See:
https://developer.android.com/training/camera/photobasics#TaskPhotoView

vs

https://developer.android.com/training/camera/photobasics#TaskPath
