### ISSUE TITLE
[Download submissions] Unicode chars replaced with "-" in filename

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#770]
Filenames were introduced in #629. Layers with accents in their name do not generate the appropriate filename, i.e. "área" becomes "-rea". Rather than replacing everything that's not [A-Za-z], perhaps we could replace spaces and punctuation only? @DakshSaini could you take a look?

**Comment by gino-m** [comment]
We missed unicode chars - maybe let's also replace:
```
  < (less than)
  > (greater than)
  : (colon - sometimes works, but is actually NTFS Alternate Data Streams)
  " (double quote)
  / (forward slash)
  \ (backslash)
  | (vertical bar or pipe)
  ? (question mark)
  * (asterisk)
```

Source: https://stackoverflow.com/a/31976060

**Comment by jcqli** [comment]
Obsolete task
