### ISSUE TITLE
[Layer Creation Dialog] Required selector doesn't work

### ISSUE THREAD

**Issue by scolsen** [google/ground-platform#774]
**Describe the bug**
When toggling "Required" for a question, the question editor closes and the state of the toggle is not updated.

**To Reproduce**
1. Add layer
2. Add a question, filling out details. Type text + Choose one.
3. Toggle  **Required**

**Expected behavior**
Toggle functions correctly and the field is marked as required.

**Screenshots**

https://user-images.githubusercontent.com/11237600/123974759-df4cd200-d98a-11eb-9677-c4c7b41a9802.mov

**Comment by scolsen** [comment]
@gino-m @DaoyuT FYI

**Comment by gino-m** [comment]
@DakshSaini Looks like this might be related to your latest change for expanding/collapsing form questions. Could you PTAL?

**Comment by DakshSaini** [comment]
@gino-m The focusout event was triggering the closing of actions and options. I have made a fix here #778
