### ISSUE TITLE
[Terms of Service] Android app crashes due to lack of permissions to ToS

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#786]
At HEAD the Android app currently is unusable since the app cannot access to `tos` in Firestore based on the deployed rules:
https://github.com/google/ground-platform/blob/master/firestore/firestore.rules

All pass listed users should have access to the tos stored in the db.

@HemanParbhakar PTAL?

**Comment by HemanParbhakar** [comment]
added this into firestore rules fixes it.
match /config/tos {
    	allow read: if canAccess(email());
    }
