### ISSUE TITLE
[Export CSV] Include contributor user name and email in exported data

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#794]

**Comment by hebertlucena** [comment]
when exporting (csv) the fields 'Place ID' and 'Place Name' are empty

**Comment by gino-m** [comment]
> when exporting (csv) the fields 'Place ID' and 'Place Name' are empty

Hi Hebert, there refer to the user-defined ID and name imported from GeoJSON in `properties`. This should be improved. #562 should add support to export all properties (including custom ID). Just filed #800 to always include a label for features when exporting, not just when specified in imported GeoJSON.
