### ISSUE TITLE
[Export CSV] Add geometries to export

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#797]
@kdyson This will make the exported CSV much larger. Is including the whole geometry in each row the most useful format for your work, or would it be more useful to export an ID or other reference?

**Comment by kdyson** [comment]
by far the easiest way to handle this is by exporting the geography in each row. because some rows are added (which have xy) and some rows match based on label, data management becomes more difficult. I don't know hwo much larger this will make it, but CEO exports the shapes with csv files and it's not that large.

**Comment by gino-m** [comment]
@kdyson I've deployed this feature to your Ground instance; downloaded CSV now contains a column with heading "GeoJSON" containing the escaped GeoJSON strings. Could you please let me know if it's working?

**Comment by kdyson** [comment]
@gino-m I see the GeoJSON column in the downloaded data. However, I can't get any other program to recognize it--it will not load properly into GEE or QGIS. If the column were WKT QGIS would take it without issue. I think the entire file needs to be geojson format, not a geojson line within a csv if using GeoJSON and not WKT is required.

**Comment by gino-m** [comment]
> @gino-m I see the GeoJSON column in the downloaded data. However, I can't get any other program to recognize it--it will not load properly into GEE or QGIS. If the column were WKT QGIS would take it without issue. I think the entire file needs to be geojson format, not a geojson line within a csv if using GeoJSON and not WKT is required. Sorry for the confusion--

Ah, good to know. If no tools support it, GeoJSON in CSV doesn't sound very useful. Someone appeared to echo this observation in [this Stack Exchange thread](https://gis.stackexchange.com/questions/226615/loading-a-csv-with-an-embedded-geojson-polygon-geometry-in-qgis). Maybe we can convert the GeoJSON to WKT using the [wkt](https://www.npmjs.com/package//wkt) NodeJS library. Let me see. 

> I've used WKT frequently in the past and didn't realize how much more difficult GeoJSON was to manage from a usability perspective.

Is GeoJSON hard to manage because of lack of support by tooling, or something about the format itself?

**Comment by kdyson** [comment]
Yep, exactly. Difficult because of lack of support by tooling!

**Comment by gino-m** [comment]
Thanks, noted! Fyi and note to self:

Earth Engine allows importing both GeoJSON and WKT columns:
https://developers.google.com/earth-engine/guides/table_upload

By trial and error I noticed that it expects the geometry column to contain a GeoJSON `Geometry`, not a full `Feature` object. Also, overriding the geometry column name on import doesn't appear to work for camel-case column names (e.g. GeoJSON).

**Comment by gino-m** [comment]
@kdyson Ok, updated #802 to hack up converting the GeoJSON geometry to WKT and deployed to your test server. Please try again?

**Comment by kdyson** [comment]
Aha! What you mention about GeoJSON geometry vs. feature is interesting. I have used the WKT and geometry column name input in GEE before. 

On first review of the WKT output--it looks like WKT is being exported only for the original polygons. Added points are as xy columns. I can import the output and have the polygons appear, and the proper information is associated with them.

**Comment by gino-m** [comment]
> On first review of the WKT output--it looks like WKT is being exported only for the original polygons. Added points are as xy columns. I can import the output and have the polygons appear, and the proper information is associated with them.

Great, glad it's working! The GeoJSON was there only for imported features. Are you able to use the lat and lng in the export to get the remaining points? If not please lmk and I can try to convert them on the fly if necessary. Eventually we plan to use the same internal representation for imported GeoJSON features as points and hand-drawing polygons. When that happens they will also be exported as WKT.

**Comment by kdyson** [comment]
Good question--they do. I just checked and they do import properly with the information. 

That plan sounds fantastic and would be much appreciated from a user standpoint.
