### ISSUE TITLE
[Code health] Integrate code coverage plugin

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#820]
- [ ] Run from command-line
- [ ] Run from GitHub on push/PR
- [ ] Show badge on GitHub repo

**Comment by os-micmec** [comment]
After a bit of research, I would like to go ahead and use [codecov.io](https://codecov.io).

I see this is already used for the android part of ground: https://app.codecov.io/gh/google/ground-android/.

I started trying it our in my fork: https://app.codecov.io/gh/os-micmec/ground-platform/, you can also see the badge at https://github.com/os-micmec/ground-platform/tree/master/web-ng

This, together with the [codecov-uploader](https://docs.codecov.com/docs/codecov-uploader) will check all the three boxes above. In the next days I will prepare a couple of commits to implement this.
