### ISSUE TITLE
[Code health] Implement unit test coverage of all non-trivial business logic

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#821]

**Comment by gino-m** [comment]
@gino-m To survey code and outline components/services in need of tests.

**Comment by gino-m** [comment]
To start:

* @os-micmec DialogService
* @gino-m DataImport
* @DaoyuT DrawingTools

**Comment by os-micmec** [comment]
For next week let's do:

- @os-micmec AuthService
- @DaoyuT FeatureService
- @gino-m NotificationService + ObservationService
