### ISSUE TITLE
Fix end-to-end angular tests

### ISSUE THREAD

**Issue by os-micmec** [google/ground-platform#830]
@gino-m reported that when running the e2e test for the Angular frontend there were errors. We should fix these.

In addition, we have also discovered we are not running the e2e tests on each PR. We should setup some action/workflow to do this.

**Comment by gino-m** [comment]
@os-micmec Iirc we disabled these? Can we close this?

**Comment by gino-m** [comment]
Please reopen if closed prematurely.
