### ISSUE TITLE
[Main map] Clicking on the edge of a polygon shows empty dialog

### ISSUE THREAD

**Issue by rachaprince** [google/ground-platform#840]
**To Reproduce**
1. Click on the edge of a polygon observation
2. An error appears:
  `Several overlapping features at this location`

**Expected behavior**
The polygon is selected with no errors

**Screenshots**

![a4CDiPGLTEKzsJh](https://user-images.githubusercontent.com/7172296/142294441-a0570380-cde6-4500-880c-cd9595e4a81f.png)

**Comment by gino-m** [comment]
@DaoyuT Could you PTAL?

**Comment by gino-m** [comment]
Just checked and this can still be reproduced. @DaoyuT and/or @nwkotto PTAL?

**Comment by gino-m** [comment]
Fix: Don't show dialog if there are no polygons.

**Comment by gino-m** [comment]
Closing in favor of #1379
