### ISSUE TITLE
UI does not show date and time fields 

### ISSUE THREAD

**Issue by rachaprince** [google/ground-platform#854]
**Describe the bug**
UI does not show date and time fields 

**To Reproduce**
1. Click on a feature that has an observation with date and/or time fields. 
2. The date and time responses do not render in the side panel 

**Expected behavior**
The date and time field responses from the observation show up in the side panel

**Comment by gino-m** [comment]
Subtask of #1100.

**Comment by gino-m** [comment]
Duplicate of #1132.
