### ISSUE TITLE
Can't deploy prod build to to Firebase hosting from local

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#925]
Deploy works, but getting the following error after deploying `prod` built on local PC using `./build.sh`:

![image](https://user-images.githubusercontent.com/228050/182063344-b9a0705e-ff26-431a-ad2e-10d7189b94a4.png)

Looking in build artifact, it seems `process.env.*` are not getting replaced with actual API keys.

To fix this we could create alternate build environments, one using the keys in the local `.*` files, and one using the `env` values set in CD.

@os-micmec Would you like to give this one a shot?

**Comment by gino-m** [comment]
@os-micmec Is local deploy working again? If so let's close this one.

**Comment by os-micmec** [comment]
This is working now!
