### ISSUE TITLE
[Export CSV] Include (client) and upload (server) date/time for each submission

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#930]

**Comment by gino-m** [comment]
@os-micmec Related to your export work

**Comment by gino-m** [comment]
+1 by Jacob @ SERVIR

**Comment by gino-m** [comment]
`data:created` and `data:uploaded` for now?

**Comment by kenstershiro** [comment]
Field names and format look good, agreed to prioritize this

**Comment by kenstershiro** [comment]
Place columns at the end of the data: columns
