### ISSUE TITLE
[Form editor] Clicking anywhere in expanded field makes it collapse

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#94]
1. "Customize" from layer overflow menu
2. Click any field to expand
3. Click any object in the field (type, option, etc.), field collapses

**Comment by gino-m** [comment]
This may have started after adding drag-to-reorder. Could you kindly take a look

**Comment by DaoyuT** [comment]
@gino-m I took a look and found out what caused this, would you like a quick meeting to talk about how to resolve this bug?

**Comment by DaoyuT** [comment]
PR #97 is ready for review
