### ISSUE TITLE
Update text_field task type to text

### ISSUE THREAD

**Issue by shobhitagarwal1612** [google/ground-platform#954]
https://github.com/google/ground-platform/blob/9a635c6837384e53a76fd61d60547abc4eb7c3cf/web/src/app/shared/converters/firebase-data-converter.ts

**Comment by h20220025** [comment]
hi @shobhitagarwal1612 @cdibona @gyarill, This issue seems to be interesting.
Can you please assign this to me?

**Comment by gino-m** [comment]
Marking obsolete in favor of shared schema
