### ISSUE TITLE
[Code health] Upgrade to latest Angular

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#965]
The following packages should be replaced or deleted:

- [x] `ngx-autosize-input`: only supports up to Angular 15
- [x] `@angular/flex-layout`: deprecated

**Comment by amysorto** [comment]
The `ngx-autosize-input` package supports v17: https://github.com/joshuawwright/ngx-autosize-input/releases/tag/17.0.1

**Comment by gino-m** [comment]
@amysorto Great. Would you like to try upgrading?

**Comment by amysorto** [comment]
Upgrading to v16 is #1764
