### ISSUE TITLE
Update handling of LOI properties on import

### ISSUE THREAD

**Issue by gino-m** [google/ground-platform#997]
Let's mirror GeoJSON's Feature spec so that attributes and properties are preserved round-trip (import-export). The correct behavior should be:

- [ ] The GeoJSON Feature's `id` should be used as `customId` for the Ground LOIs.
- [ ] Feature properties are copied to Ground LOI's `properties` map exactly as they appear.
- [ ] `caption` in  LO can be removed. We'll look in the `name` properties when showing a label for the Feature in the UI.

**Comment by jcqli** [comment]
@gino-m Is this clsoed with #1242 ?
